### Save all PBP point  data

In [15]:
import pandas as pd
import numpy as np
import json
import os

pd.set_option('display.max_columns', None)
pd.set_option("display.max_rows", None)
import sys
sys.path.append('../src')

from process import get_match_info, get_match_point_level_info
from search_utils import get_unique_player_ids, normalize_name, get_all_players_info, get_all_players_info_df

In [16]:
def create_directory(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)

tournament_list = ['australian_open', 'roland_garros']
league_list = ['atp', 'wta']

players_matches_catalogue_folder = 'players_matches_catalogue'
create_directory(players_matches_catalogue_folder)

catalogue_csv_path = os.path.join(players_matches_catalogue_folder, 'catalogue_all_matches_available.csv')

if os.path.exists(catalogue_csv_path):
    os.remove(catalogue_csv_path)

for tournament in tournament_list:
    for league in league_list:
        dir_name = '../all_json/' + tournament + '/' + league + '/'
        csv_save_path = os.path.join('pbp_data_csvs', tournament)
        create_directory(csv_save_path)
        csv_save_path = os.path.join(csv_save_path, league)
        create_directory(csv_save_path)
        
        for filename in os.listdir(dir_name):
            if filename.endswith(".json"):
                print(filename)
                with open(os.path.join(dir_name, filename)) as file_name:
                    tracking_data_json = json.load(file_name)
                    file_year = [int(s) for s in filename.split('_') if s.isdigit()]
                    
                    match_id = filename[17:-19]
                    match_pbp_data =  get_match_point_level_info(tracking_data_json)
                    hasYearInMatchId = ""
                    if tournament == "roland_garros":
                        hasYearInMatchId = str(file_year[0]) + '_'
                        
                    save_data_filename = league + '_' + tournament +  '_' + hasYearInMatchId + match_id + '_pbp' + '.csv'
                    save_data_path = os.path.join(csv_save_path, save_data_filename)
                    
                    #Add scores
                    
                    match_pbp_data.to_csv(save_data_path, index=False)
                    
                    match_catalogue_data = get_match_info(tracking_data_json, tournament, league, match_id, str(file_year[0]))
                    
                    match_catalogue_data.to_csv(catalogue_csv_path, mode='a', index=False, header=not os.path.exists(catalogue_csv_path))

            else:
                continue

atp_AO_Open_year_2020_MS101_tracking_data.json
atp_AO_Open_year_2020_MS102_tracking_data.json
atp_AO_Open_year_2020_MS103_tracking_data.json
atp_AO_Open_year_2020_MS104_tracking_data.json
atp_AO_Open_year_2020_MS105_tracking_data.json
atp_AO_Open_year_2020_MS106_tracking_data.json
atp_AO_Open_year_2020_MS107_tracking_data.json
atp_AO_Open_year_2020_MS108_tracking_data.json
atp_AO_Open_year_2020_MS109_tracking_data.json
atp_AO_Open_year_2020_MS110_tracking_data.json
atp_AO_Open_year_2020_MS111_tracking_data.json
atp_AO_Open_year_2020_MS112_tracking_data.json
atp_AO_Open_year_2020_MS113_tracking_data.json
atp_AO_Open_year_2020_MS114_tracking_data.json
atp_AO_Open_year_2020_MS115_tracking_data.json
atp_AO_Open_year_2020_MS116_tracking_data.json
atp_AO_Open_year_2020_MS117_tracking_data.json
atp_AO_Open_year_2020_MS118_tracking_data.json
atp_AO_Open_year_2020_MS120_tracking_data.json
atp_AO_Open_year_2020_MS121_tracking_data.json
atp_AO_Open_year_2020_MS122_tracking_data.json
atp_AO_Open_year_2020_MS123_tracking_data.json
atp_AO_Open_year_2020_MS124_tracking_data.json
atp_AO_Open_year_2020_MS125_tracking_data.json
atp_AO_Open_year_2020_MS126_tracking_data.json
atp_AO_Open_year_2020_MS127_tracking_data.json
atp_AO_Open_year_2020_MS128_tracking_data.json
atp_AO_Open_year_2020_MS129_tracking_data.json
atp_AO_Open_year_2020_MS130_tracking_data.json
atp_AO_Open_year_2020_MS131_tracking_data.json
atp_AO_Open_year_2020_MS132_tracking_data.json
atp_AO_Open_year_2020_MS133_tracking_data.json
atp_AO_Open_year_2020_MS134_tracking_data.json
atp_AO_Open_year_2020_MS135_tracking_data.json
atp_AO_Open_year_2020_MS136_tracking_data.json
atp_AO_Open_year_2020_MS137_tracking_data.json
atp_AO_Open_year_2020_MS138_tracking_data.json
atp_AO_Open_year_2020_MS139_tracking_data.json
atp_AO_Open_year_2020_MS140_tracking_data.json
atp_AO_Open_year_2020_MS141_tracking_data.json
atp_AO_Open_year_2020_MS142_tracking_data.json
atp_AO_Open_year_2020_MS143_tracking_data.json
atp_AO_Open_year_2020_MS144_tracking_data.json
atp_AO_Open_year_2020_MS145_tracking_data.json
atp_AO_Open_year_2020_MS146_tracking_data.json
atp_AO_Open_year_2020_MS147_tracking_data.json
atp_AO_Open_year_2020_MS148_tracking_data.json
atp_AO_Open_year_2020_MS150_tracking_data.json
atp_AO_Open_year_2020_MS151_tracking_data.json
atp_AO_Open_year_2020_MS152_tracking_data.json
atp_AO_Open_year_2020_MS153_tracking_data.json
atp_AO_Open_year_2020_MS154_tracking_data.json
atp_AO_Open_year_2020_MS155_tracking_data.json
atp_AO_Open_year_2020_MS156_tracking_data.json
atp_AO_Open_year_2020_MS157_tracking_data.json
atp_AO_Open_year_2020_MS158_tracking_data.json
atp_AO_Open_year_2020_MS159_tracking_data.json
atp_AO_Open_year_2020_MS160_tracking_data.json
atp_AO_Open_year_2020_MS161_tracking_data.json
atp_AO_Open_year_2020_MS162_tracking_data.json
atp_AO_Open_year_2020_MS163_tracking_data.json
atp_AO_Open_year_2020_MS164_tracking_data.json
atp_AO_Open_year_2020_MS201_tracking_data.json
atp_AO_Open_year_2020_MS202_tracking_data.json
atp_AO_Open_year_2020_MS203_tracking_data.json
atp_AO_Open_year_2020_MS204_tracking_data.json
atp_AO_Open_year_2020_MS205_tracking_data.json
atp_AO_Open_year_2020_MS206_tracking_data.json
atp_AO_Open_year_2020_MS207_tracking_data.json
atp_AO_Open_year_2020_MS208_tracking_data.json
atp_AO_Open_year_2020_MS209_tracking_data.json
atp_AO_Open_year_2020_MS210_tracking_data.json
atp_AO_Open_year_2020_MS211_tracking_data.json
atp_AO_Open_year_2020_MS212_tracking_data.json
atp_AO_Open_year_2020_MS213_tracking_data.json
atp_AO_Open_year_2020_MS214_tracking_data.json
atp_AO_Open_year_2020_MS215_tracking_data.json
atp_AO_Open_year_2020_MS216_tracking_data.json
atp_AO_Open_year_2020_MS217_tracking_data.json
atp_AO_Open_year_2020_MS218_tracking_data.json
atp_AO_Open_year_2020_MS219_tracking_data.json
atp_AO_Open_year_2020_MS220_tracking_data.json
atp_AO_Open_year_2020_MS221_tracking_data.json
atp_AO_Open_year_2020_MS222_tracking_data.json
atp_AO_Open_year_2020_MS223_tracking_data.json
atp_AO_Open_year_2020_MS224_tracking_data.json
atp_AO_Open_year_2020_MS226_tracking_data.json
atp_AO_Open_year_2020_MS227_tracking_data.json
atp_AO_Open_year_2020_MS228_tracking_data.json
atp_AO_Open_year_2020_MS229_tracking_data.json
atp_AO_Open_year_2020_MS230_tracking_data.json
atp_AO_Open_year_2020_MS231_tracking_data.json
atp_AO_Open_year_2020_MS232_tracking_data.json
atp_AO_Open_year_2020_MS301_tracking_data.json
atp_AO_Open_year_2020_MS302_tracking_data.json
atp_AO_Open_year_2020_MS303_tracking_data.json
atp_AO_Open_year_2020_MS304_tracking_data.json
atp_AO_Open_year_2020_MS305_tracking_data.json
atp_AO_Open_year_2020_MS306_tracking_data.json
atp_AO_Open_year_2020_MS307_tracking_data.json
atp_AO_Open_year_2020_MS308_tracking_data.json
atp_AO_Open_year_2020_MS309_tracking_data.json
atp_AO_Open_year_2020_MS310_tracking_data.json
atp_AO_Open_year_2020_MS311_tracking_data.json
atp_AO_Open_year_2020_MS312_tracking_data.json
atp_AO_Open_year_2020_MS313_tracking_data.json
atp_AO_Open_year_2020_MS314_tracking_data.json
atp_AO_Open_year_2020_MS315_tracking_data.json
atp_AO_Open_year_2020_MS316_tracking_data.json
atp_AO_Open_year_2020_MS401_tracking_data.json
atp_AO_Open_year_2020_MS402_tracking_data.json
atp_AO_Open_year_2020_MS403_tracking_data.json
atp_AO_Open_year_2020_MS404_tracking_data.json
atp_AO_Open_year_2020_MS405_tracking_data.json
atp_AO_Open_year_2020_MS406_tracking_data.json
atp_AO_Open_year_2020_MS407_tracking_data.json
atp_AO_Open_year_2020_MS408_tracking_data.json
atp_AO_Open_year_2020_MS501_tracking_data.json
atp_AO_Open_year_2020_MS502_tracking_data.json
atp_AO_Open_year_2020_MS503_tracking_data.json
atp_AO_Open_year_2020_MS504_tracking_data.json
atp_AO_Open_year_2020_MS601_tracking_data.json
atp_AO_Open_year_2020_MS602_tracking_data.json
atp_AO_Open_year_2020_MS701_tracking_data.json
atp_AO_Open_year_2021_MS101_tracking_data.json
atp_AO_Open_year_2021_MS102_tracking_data.json
atp_AO_Open_year_2021_MS103_tracking_data.json
atp_AO_Open_year_2021_MS104_tracking_data.json
atp_AO_Open_year_2021_MS105_tracking_data.json
Could not get score columns...
atp_AO_Open_year_2021_MS106_tracking_data.json
Could not get score columns...
atp_AO_Open_year_2021_MS107_tracking_data.json
atp_AO_Open_year_2021_MS108_tracking_data.json
atp_AO_Open_year_2021_MS109_tracking_data.json
atp_AO_Open_year_2021_MS110_tracking_data.json
atp_AO_Open_year_2021_MS111_tracking_data.json
Could not get score columns...
atp_AO_Open_year_2021_MS112_tracking_data.json
atp_AO_Open_year_2021_MS113_tracking_data.json
atp_AO_Open_year_2021_MS114_tracking_data.json
atp_AO_Open_year_2021_MS115_tracking_data.json
atp_AO_Open_year_2021_MS116_tracking_data.json
atp_AO_Open_year_2021_MS117_tracking_data.json
atp_AO_Open_year_2021_MS118_tracking_data.json
atp_AO_Open_year_2021_MS119_tracking_data.json
atp_AO_Open_year_2021_MS120_tracking_data.json
atp_AO_Open_year_2021_MS121_tracking_data.json
atp_AO_Open_year_2021_MS122_tracking_data.json
atp_AO_Open_year_2021_MS123_tracking_data.json
atp_AO_Open_year_2021_MS124_tracking_data.json
atp_AO_Open_year_2021_MS125_tracking_data.json
atp_AO_Open_year_2021_MS126_tracking_data.json
atp_AO_Open_year_2021_MS127_tracking_data.json
atp_AO_Open_year_2021_MS128_tracking_data.json
atp_AO_Open_year_2021_MS129_tracking_data.json
atp_AO_Open_year_2021_MS130_tracking_data.json
atp_AO_Open_year_2021_MS131_tracking_data.json
atp_AO_Open_year_2021_MS132_tracking_data.json
atp_AO_Open_year_2021_MS133_tracking_data.json
atp_AO_Open_year_2021_MS134_tracking_data.json
atp_AO_Open_year_2021_MS135_tracking_data.json
atp_AO_Open_year_2021_MS136_tracking_data.json
atp_AO_Open_year_2021_MS137_tracking_data.json
atp_AO_Open_year_2021_MS138_tracking_data.json
atp_AO_Open_year_2021_MS139_tracking_data.json
atp_AO_Open_year_2021_MS140_tracking_data.json
atp_AO_Open_year_2021_MS141_tracking_data.json
atp_AO_Open_year_2021_MS142_tracking_data.json
atp_AO_Open_year_2021_MS143_tracking_data.json
atp_AO_Open_year_2021_MS144_tracking_data.json
atp_AO_Open_year_2021_MS145_tracking_data.json
atp_AO_Open_year_2021_MS146_tracking_data.json
atp_AO_Open_year_2021_MS147_tracking_data.json
atp_AO_Open_year_2021_MS148_tracking_data.json
atp_AO_Open_year_2021_MS149_tracking_data.json
atp_AO_Open_year_2021_MS150_tracking_data.json
atp_AO_Open_year_2021_MS151_tracking_data.json
atp_AO_Open_year_2021_MS152_tracking_data.json
atp_AO_Open_year_2021_MS153_tracking_data.json
atp_AO_Open_year_2021_MS154_tracking_data.json
atp_AO_Open_year_2021_MS155_tracking_data.json
atp_AO_Open_year_2021_MS156_tracking_data.json
atp_AO_Open_year_2021_MS157_tracking_data.json
atp_AO_Open_year_2021_MS158_tracking_data.json
atp_AO_Open_year_2021_MS159_tracking_data.json
atp_AO_Open_year_2021_MS160_tracking_data.json
atp_AO_Open_year_2021_MS161_tracking_data.json
atp_AO_Open_year_2021_MS162_tracking_data.json
atp_AO_Open_year_2021_MS163_tracking_data.json
atp_AO_Open_year_2021_MS164_tracking_data.json
atp_AO_Open_year_2021_MS201_tracking_data.json
atp_AO_Open_year_2021_MS202_tracking_data.json
atp_AO_Open_year_2021_MS203_tracking_data.json
atp_AO_Open_year_2021_MS204_tracking_data.json
atp_AO_Open_year_2021_MS205_tracking_data.json
atp_AO_Open_year_2021_MS206_tracking_data.json
atp_AO_Open_year_2021_MS207_tracking_data.json
atp_AO_Open_year_2021_MS208_tracking_data.json
atp_AO_Open_year_2021_MS209_tracking_data.json
atp_AO_Open_year_2021_MS210_tracking_data.json
atp_AO_Open_year_2021_MS211_tracking_data.json
atp_AO_Open_year_2021_MS212_tracking_data.json
atp_AO_Open_year_2021_MS213_tracking_data.json
atp_AO_Open_year_2021_MS214_tracking_data.json
atp_AO_Open_year_2021_MS215_tracking_data.json
atp_AO_Open_year_2021_MS216_tracking_data.json
atp_AO_Open_year_2021_MS217_tracking_data.json
atp_AO_Open_year_2021_MS218_tracking_data.json
atp_AO_Open_year_2021_MS219_tracking_data.json
atp_AO_Open_year_2021_MS220_tracking_data.json
atp_AO_Open_year_2021_MS221_tracking_data.json
atp_AO_Open_year_2021_MS222_tracking_data.json
atp_AO_Open_year_2021_MS223_tracking_data.json
atp_AO_Open_year_2021_MS224_tracking_data.json
atp_AO_Open_year_2021_MS225_tracking_data.json
atp_AO_Open_year_2021_MS226_tracking_data.json
atp_AO_Open_year_2021_MS227_tracking_data.json
atp_AO_Open_year_2021_MS228_tracking_data.json
atp_AO_Open_year_2021_MS229_tracking_data.json
atp_AO_Open_year_2021_MS230_tracking_data.json
atp_AO_Open_year_2021_MS231_tracking_data.json
atp_AO_Open_year_2021_MS232_tracking_data.json
atp_AO_Open_year_2021_MS301_tracking_data.json
atp_AO_Open_year_2021_MS302_tracking_data.json
atp_AO_Open_year_2021_MS303_tracking_data.json
atp_AO_Open_year_2021_MS304_tracking_data.json
atp_AO_Open_year_2021_MS305_tracking_data.json
atp_AO_Open_year_2021_MS306_tracking_data.json
atp_AO_Open_year_2021_MS307_tracking_data.json
atp_AO_Open_year_2021_MS308_tracking_data.json
atp_AO_Open_year_2021_MS309_tracking_data.json
atp_AO_Open_year_2021_MS310_tracking_data.json
atp_AO_Open_year_2021_MS311_tracking_data.json
atp_AO_Open_year_2021_MS312_tracking_data.json
atp_AO_Open_year_2021_MS313_tracking_data.json
atp_AO_Open_year_2021_MS314_tracking_data.json
atp_AO_Open_year_2021_MS315_tracking_data.json
atp_AO_Open_year_2021_MS316_tracking_data.json
atp_AO_Open_year_2021_MS401_tracking_data.json
atp_AO_Open_year_2021_MS402_tracking_data.json
atp_AO_Open_year_2021_MS403_tracking_data.json
atp_AO_Open_year_2021_MS404_tracking_data.json
atp_AO_Open_year_2021_MS405_tracking_data.json
atp_AO_Open_year_2021_MS406_tracking_data.json
atp_AO_Open_year_2021_MS408_tracking_data.json
atp_AO_Open_year_2021_MS501_tracking_data.json
atp_AO_Open_year_2021_MS502_tracking_data.json
atp_AO_Open_year_2021_MS503_tracking_data.json
atp_AO_Open_year_2021_MS504_tracking_data.json
atp_AO_Open_year_2021_MS601_tracking_data.json
atp_AO_Open_year_2021_MS602_tracking_data.json
atp_AO_Open_year_2021_MS701_tracking_data.json
atp_AO_Open_year_2022_MS101_tracking_data.json
atp_AO_Open_year_2022_MS102_tracking_data.json
atp_AO_Open_year_2022_MS103_tracking_data.json
atp_AO_Open_year_2022_MS104_tracking_data.json
atp_AO_Open_year_2022_MS105_tracking_data.json
atp_AO_Open_year_2022_MS106_tracking_data.json
atp_AO_Open_year_2022_MS107_tracking_data.json
atp_AO_Open_year_2022_MS108_tracking_data.json
atp_AO_Open_year_2022_MS109_tracking_data.json
atp_AO_Open_year_2022_MS110_tracking_data.json
atp_AO_Open_year_2022_MS111_tracking_data.json
atp_AO_Open_year_2022_MS112_tracking_data.json
atp_AO_Open_year_2022_MS113_tracking_data.json
atp_AO_Open_year_2022_MS114_tracking_data.json
atp_AO_Open_year_2022_MS115_tracking_data.json
atp_AO_Open_year_2022_MS116_tracking_data.json
atp_AO_Open_year_2022_MS117_tracking_data.json
atp_AO_Open_year_2022_MS118_tracking_data.json
atp_AO_Open_year_2022_MS119_tracking_data.json
atp_AO_Open_year_2022_MS120_tracking_data.json
atp_AO_Open_year_2022_MS121_tracking_data.json
atp_AO_Open_year_2022_MS122_tracking_data.json
atp_AO_Open_year_2022_MS123_tracking_data.json
atp_AO_Open_year_2022_MS124_tracking_data.json
atp_AO_Open_year_2022_MS125_tracking_data.json
atp_AO_Open_year_2022_MS126_tracking_data.json
atp_AO_Open_year_2022_MS127_tracking_data.json
atp_AO_Open_year_2022_MS128_tracking_data.json
atp_AO_Open_year_2022_MS129_tracking_data.json
atp_AO_Open_year_2022_MS130_tracking_data.json
atp_AO_Open_year_2022_MS131_tracking_data.json
atp_AO_Open_year_2022_MS132_tracking_data.json
atp_AO_Open_year_2022_MS133_tracking_data.json
atp_AO_Open_year_2022_MS134_tracking_data.json
atp_AO_Open_year_2022_MS135_tracking_data.json
atp_AO_Open_year_2022_MS136_tracking_data.json
atp_AO_Open_year_2022_MS137_tracking_data.json
atp_AO_Open_year_2022_MS138_tracking_data.json
atp_AO_Open_year_2022_MS139_tracking_data.json
atp_AO_Open_year_2022_MS140_tracking_data.json
atp_AO_Open_year_2022_MS141_tracking_data.json
atp_AO_Open_year_2022_MS142_tracking_data.json
atp_AO_Open_year_2022_MS143_tracking_data.json
atp_AO_Open_year_2022_MS144_tracking_data.json
atp_AO_Open_year_2022_MS145_tracking_data.json
atp_AO_Open_year_2022_MS146_tracking_data.json
atp_AO_Open_year_2022_MS147_tracking_data.json
atp_AO_Open_year_2022_MS148_tracking_data.json
atp_AO_Open_year_2022_MS149_tracking_data.json
atp_AO_Open_year_2022_MS150_tracking_data.json
atp_AO_Open_year_2022_MS151_tracking_data.json
atp_AO_Open_year_2022_MS152_tracking_data.json
atp_AO_Open_year_2022_MS153_tracking_data.json
atp_AO_Open_year_2022_MS154_tracking_data.json
atp_AO_Open_year_2022_MS155_tracking_data.json
atp_AO_Open_year_2022_MS156_tracking_data.json
atp_AO_Open_year_2022_MS157_tracking_data.json
atp_AO_Open_year_2022_MS158_tracking_data.json
atp_AO_Open_year_2022_MS159_tracking_data.json
atp_AO_Open_year_2022_MS160_tracking_data.json
atp_AO_Open_year_2022_MS161_tracking_data.json
atp_AO_Open_year_2022_MS162_tracking_data.json
atp_AO_Open_year_2022_MS163_tracking_data.json
atp_AO_Open_year_2022_MS164_tracking_data.json
atp_AO_Open_year_2022_MS201_tracking_data.json
atp_AO_Open_year_2022_MS202_tracking_data.json
atp_AO_Open_year_2022_MS203_tracking_data.json
atp_AO_Open_year_2022_MS204_tracking_data.json
atp_AO_Open_year_2022_MS205_tracking_data.json
atp_AO_Open_year_2022_MS206_tracking_data.json
atp_AO_Open_year_2022_MS207_tracking_data.json
atp_AO_Open_year_2022_MS208_tracking_data.json
atp_AO_Open_year_2022_MS209_tracking_data.json
atp_AO_Open_year_2022_MS210_tracking_data.json
atp_AO_Open_year_2022_MS211_tracking_data.json
atp_AO_Open_year_2022_MS212_tracking_data.json
atp_AO_Open_year_2022_MS213_tracking_data.json
atp_AO_Open_year_2022_MS214_tracking_data.json
atp_AO_Open_year_2022_MS215_tracking_data.json
atp_AO_Open_year_2022_MS216_tracking_data.json
atp_AO_Open_year_2022_MS217_tracking_data.json
atp_AO_Open_year_2022_MS218_tracking_data.json
atp_AO_Open_year_2022_MS219_tracking_data.json
atp_AO_Open_year_2022_MS220_tracking_data.json
atp_AO_Open_year_2022_MS221_tracking_data.json
atp_AO_Open_year_2022_MS222_tracking_data.json
atp_AO_Open_year_2022_MS223_tracking_data.json
atp_AO_Open_year_2022_MS224_tracking_data.json
atp_AO_Open_year_2022_MS225_tracking_data.json
atp_AO_Open_year_2022_MS226_tracking_data.json
atp_AO_Open_year_2022_MS228_tracking_data.json
atp_AO_Open_year_2022_MS229_tracking_data.json
atp_AO_Open_year_2022_MS230_tracking_data.json
atp_AO_Open_year_2022_MS231_tracking_data.json
atp_AO_Open_year_2022_MS232_tracking_data.json
atp_AO_Open_year_2022_MS301_tracking_data.json
atp_AO_Open_year_2022_MS302_tracking_data.json
atp_AO_Open_year_2022_MS303_tracking_data.json
atp_AO_Open_year_2022_MS304_tracking_data.json
atp_AO_Open_year_2022_MS305_tracking_data.json
atp_AO_Open_year_2022_MS306_tracking_data.json
atp_AO_Open_year_2022_MS307_tracking_data.json
atp_AO_Open_year_2022_MS308_tracking_data.json
atp_AO_Open_year_2022_MS309_tracking_data.json
atp_AO_Open_year_2022_MS310_tracking_data.json
atp_AO_Open_year_2022_MS311_tracking_data.json
atp_AO_Open_year_2022_MS312_tracking_data.json
atp_AO_Open_year_2022_MS313_tracking_data.json
atp_AO_Open_year_2022_MS314_tracking_data.json
atp_AO_Open_year_2022_MS315_tracking_data.json
atp_AO_Open_year_2022_MS316_tracking_data.json
atp_AO_Open_year_2022_MS401_tracking_data.json
atp_AO_Open_year_2022_MS402_tracking_data.json
atp_AO_Open_year_2022_MS403_tracking_data.json
atp_AO_Open_year_2022_MS404_tracking_data.json
atp_AO_Open_year_2022_MS405_tracking_data.json
atp_AO_Open_year_2022_MS406_tracking_data.json
atp_AO_Open_year_2022_MS407_tracking_data.json
atp_AO_Open_year_2022_MS408_tracking_data.json
atp_AO_Open_year_2022_MS501_tracking_data.json
atp_AO_Open_year_2022_MS502_tracking_data.json
atp_AO_Open_year_2022_MS503_tracking_data.json
atp_AO_Open_year_2022_MS504_tracking_data.json
atp_AO_Open_year_2022_MS601_tracking_data.json
atp_AO_Open_year_2022_MS602_tracking_data.json
atp_AO_Open_year_2022_MS701_tracking_data.json
atp_AO_Open_year_2023_MS101_tracking_data.json
atp_AO_Open_year_2023_MS102_tracking_data.json
atp_AO_Open_year_2023_MS103_tracking_data.json
atp_AO_Open_year_2023_MS104_tracking_data.json
atp_AO_Open_year_2023_MS105_tracking_data.json
atp_AO_Open_year_2023_MS106_tracking_data.json
atp_AO_Open_year_2023_MS107_tracking_data.json
atp_AO_Open_year_2023_MS108_tracking_data.json
atp_AO_Open_year_2023_MS109_tracking_data.json
atp_AO_Open_year_2023_MS110_tracking_data.json
atp_AO_Open_year_2023_MS111_tracking_data.json
atp_AO_Open_year_2023_MS112_tracking_data.json
atp_AO_Open_year_2023_MS113_tracking_data.json
atp_AO_Open_year_2023_MS114_tracking_data.json
atp_AO_Open_year_2023_MS115_tracking_data.json
atp_AO_Open_year_2023_MS116_tracking_data.json
atp_AO_Open_year_2023_MS117_tracking_data.json
atp_AO_Open_year_2023_MS118_tracking_data.json
atp_AO_Open_year_2023_MS119_tracking_data.json
atp_AO_Open_year_2023_MS120_tracking_data.json
atp_AO_Open_year_2023_MS121_tracking_data.json
atp_AO_Open_year_2023_MS122_tracking_data.json
atp_AO_Open_year_2023_MS123_tracking_data.json
atp_AO_Open_year_2023_MS124_tracking_data.json
atp_AO_Open_year_2023_MS125_tracking_data.json
atp_AO_Open_year_2023_MS126_tracking_data.json
atp_AO_Open_year_2023_MS127_tracking_data.json
atp_AO_Open_year_2023_MS128_tracking_data.json
atp_AO_Open_year_2023_MS129_tracking_data.json
atp_AO_Open_year_2023_MS130_tracking_data.json
atp_AO_Open_year_2023_MS131_tracking_data.json
atp_AO_Open_year_2023_MS132_tracking_data.json
atp_AO_Open_year_2023_MS133_tracking_data.json
atp_AO_Open_year_2023_MS134_tracking_data.json
atp_AO_Open_year_2023_MS135_tracking_data.json
atp_AO_Open_year_2023_MS136_tracking_data.json
atp_AO_Open_year_2023_MS137_tracking_data.json
atp_AO_Open_year_2023_MS138_tracking_data.json
atp_AO_Open_year_2023_MS139_tracking_data.json
atp_AO_Open_year_2023_MS140_tracking_data.json
atp_AO_Open_year_2023_MS141_tracking_data.json
atp_AO_Open_year_2023_MS142_tracking_data.json
atp_AO_Open_year_2023_MS143_tracking_data.json
atp_AO_Open_year_2023_MS144_tracking_data.json
atp_AO_Open_year_2023_MS145_tracking_data.json
atp_AO_Open_year_2023_MS146_tracking_data.json
atp_AO_Open_year_2023_MS147_tracking_data.json

## Save all players

In [17]:

catalogue_df = pd.read_csv("players_matches_catalogue/catalogue_all_matches_available.csv")

player_id_mapping = {}

for index, row in catalogue_df.iterrows():
    player1_name = row['player1']
    player2_name = row['player2']
    player1_id = row['player1_id']
    player2_id = row['player2_id']
    tournament = row['tournament']

    player_id_mapping.setdefault(tournament, {})
    player_id_mapping[tournament][player1_name] = player1_id
    player_id_mapping[tournament][player2_name] = player2_id

def get_player_id(player_name, tournament):
    if tournament in player_id_mapping:
        return player_id_mapping[tournament].get(player_name, None)
    else:
        return None

player_name = 'R.NADAL'
tournament = 'roland_garros'
player_id = get_player_id(player_name, tournament)
print("Player ID for", player_name, "in", tournament, ":", player_id)

Player ID for R.NADAL in roland_garros : 7792

### Fix catalogue names

In [18]:
catalogue_path = "players_matches_catalogue/catalogue_all_matches_available.csv"
catalogue_df = pd.read_csv(catalogue_path)

In [19]:
if 'player1' in catalogue_df.columns and 'player2' in catalogue_df.columns:
    catalogue_df['player1'] = catalogue_df['player1'].apply(normalize_name)
    catalogue_df['player2'] = catalogue_df['player2'].apply(normalize_name)

catalogue_df.to_csv(catalogue_path, index=False)

saved_catalogue_df = pd.read_csv(catalogue_path)
saved_catalogue_df.head(5)

,year,player1,player2,player1_id,player2_id,player1_country,player2_country,player1_seed,player2_seed,court_name,court_id,num_sets_completed,match_type,match_status,match_id,tournament,league
0,2020,R.NADAL,H.DELLIEN,ATPN409,ATPDA31,ESP,BOL,1.0,NaN,Rod Laver Arena,1,3,Men's Singles,C,2020_MS101,australian_open,atp
1,2020,F.DELBONIS,J.SOUSA,ATPD874,ATPSH90,ARG,POR,NaN,NaN,Court 19,21,3,Men's Singles,C,2020_MS102,australian_open,atp
2,2020,C.EUBANKS,P.GOJOWCZYK,ATPE865,ATPG967,USA,GER,NaN,NaN,Court 5,7,4,Men's Singles,C,2020_MS103,australian_open,atp
3,2020,J.KOVALIK,P.CARRENOBUSTA,ATPKC04,ATPCD85,SVK,ESP,NaN,27.0,Court 13,15,4,Men's Singles,C,2020_MS104,australian_open,atp
4,2020,N.KYRGIOS,L.SONEGO,ATPKE17,ATPSU87,AUS,ITA,23.0,NaN,Melbourne Arena,3,3,Men's Singles,C,2020_MS105,australian_open,atp

In [20]:
name_replacements = {
    'JM.DELPOTRO': 'J.DELPOTRO',
    'JL.STRUFF': 'J.STRUFF',
    'JW.TSONGA' : 'J.TSONGA',
    'PH.HERBERT': 'P.HERBERT',
    'DE.GALAN': 'D.GALAN',
    'AK.SCHMIEDLOVA': 'A.SCHMIEDLOVA',
    'C.SUÁREZNAVARRO': 'C.SUAREZNAVARRO',
    'PM.TIG': 'P.TIG',
    'F.AUGER-ALIASSIME': 'F.AUGERALIASSIME',
    'JI.LONDERO': 'J.LONDERO',
    'CH.TSENG': 'C.TSENG',
    'JP.VARILLAS': 'J.VARILLAS',
    'TM.ETCHEVERRY': 'T.ETCHEVERRY',
    'JJ.WOLF': 'J.WOLF'
}

for old_name, new_name in name_replacements.items():
    catalogue_df.loc[catalogue_df['player1'] == old_name, 'player1'] = new_name
    catalogue_df.loc[catalogue_df['player2'] == old_name, 'player2'] = new_name

catalogue_df.to_csv(catalogue_path, index=False)

saved_catalogue_df = pd.read_csv(catalogue_path)
saved_catalogue_df.head(5)

,year,player1,player2,player1_id,player2_id,player1_country,player2_country,player1_seed,player2_seed,court_name,court_id,num_sets_completed,match_type,match_status,match_id,tournament,league
0,2020,R.NADAL,H.DELLIEN,ATPN409,ATPDA31,ESP,BOL,1.0,NaN,Rod Laver Arena,1,3,Men's Singles,C,2020_MS101,australian_open,atp
1,2020,F.DELBONIS,J.SOUSA,ATPD874,ATPSH90,ARG,POR,NaN,NaN,Court 19,21,3,Men's Singles,C,2020_MS102,australian_open,atp
2,2020,C.EUBANKS,P.GOJOWCZYK,ATPE865,ATPG967,USA,GER,NaN,NaN,Court 5,7,4,Men's Singles,C,2020_MS103,australian_open,atp
3,2020,J.KOVALIK,P.CARRENOBUSTA,ATPKC04,ATPCD85,SVK,ESP,NaN,27.0,Court 13,15,4,Men's Singles,C,2020_MS104,australian_open,atp
4,2020,N.KYRGIOS,L.SONEGO,ATPKE17,ATPSU87,AUS,ITA,23.0,NaN,Melbourne Arena,3,3,Men's Singles,C,2020_MS105,australian_open,atp

In [21]:
catalogue_path = "players_matches_catalogue/catalogue_all_matches_available.csv"
catalogue_df = pd.read_csv(catalogue_path)
australian_open_ids = get_unique_player_ids(catalogue_df, 'australian_open')
roland_garros_ids = get_unique_player_ids(catalogue_df, 'roland_garros')

print("Unique player IDs from Australian Open:", australian_open_ids)
print("Unique player IDs from Roland Garros:", roland_garros_ids)

Unique player IDs from Australian Open: {'WTA316959', 'ATPQ927', 'ATPBS86', 'WTA313485', 'ATPMQ75', 'ATPTC12', 'WTA310770', 'ATPC977', 'WTA312413', 'ATPD0C1', 'ATPKE73', 'ATPHH06', 'WTA317810', 'WTA317708', 'ATPTE30', 'ATPGE33', 'ATPHG86', 'WTA319526', 'WTA315616', 'WTA312001', 'ATPKI95', 'WTA314429', 'WTA322534', 'ATPKB95', 'WTA325725', 'ATPRH16', 'WTA313968', 'ATPCG33', 'WTA315427', 'ATPWB32', 'ATPGA36', 'WTA320728', 'ATPD643', 'ATPDA31', 'ATPPL56', 'ATPMD56', 'WTA315696', 'ATPCE77', 'ATPRE44', 'ATPD923', 'ATPM0CI', 'WTA326376', 'ATPKE29', 'ATPKF17', 'ATPJ553', 'WTA329627', 'WTA318516', 'WTA328896', 'ATPV836', 'WTA327793', 'ATPGJ37', 'WTA110536', 'ATPS0IA', 'ATPW09G', 'ATPS0H2', 'ATPH756', 'WTA316159', 'ATPR975', 'ATPTA12', 'WTA323942', 'ATPEA24', 'WTA311779', 'WTA310775', 'ATPM0NI', 'ATPV708', 'WTA320313', 'WTA328120', 'WTA317414', 'WTA319489', 'ATPRH24', 'ATPG628', 'WTA314584', 'ATPH09P', 'WTA327573', 'ATPML57', 'WTA315030', 'WTA323802', 'WTA310440', 'ATPKC56', 'WTA310926', 'ATPBK24', 'WTA315232', 'WTA314464', 'ATPSC77', 'ATPE873', 'WTA323966', 'WTA330291', 'WTA324166', 'ATPSX91', 'WTA312536', 'WTA327620', 'ATPV0DZ', 'WTA320124', 'WTA317175', 'WTA160515', 'ATPBT72', 'WTA313381', 'ATPE865', 'ATPCF01', 'WTA317819', 'ATPH09F', 'WTA318203', 'WTA316344', 'ATPK435', 'ATPPD07', 'WTA325940', 'WTA317306', 'WTA312121', 'ATPT840', 'ATPK0A3', 'WTA331545', 'WTA313796', 'WTA312673', 'ATPKE17', 'WTA318314', 'WTA316925', 'ATPPF39', 'ATPK0DP', 'WTA320543', 'ATPZ0A1', 'ATPAE14', 'WTA325898', 'WTA317584', 'ATPG967', 'ATPHB29', 'WTA319280', 'ATPCG80', 'ATPTA46', 'ATPSU87', 'ATPZ371', 'WTA310137', 'ATPBK40', 'WTA314610', 'WTA317155', 'ATPW367', 'WTA326101', 'WTA319007', 'WTA323079', 'WTA312328', 'WTA160471', 'WTA316286', 'WTA320016', 'ATPMW02', 'WTA323149', 'WTA313349', 'WTA318425', 'ATPK09F', 'ATPSN54', 'WTA317171', 'ATPMJ08', 'WTA329393', 'ATPV812', 'WTA317964', 'WTA311470', 'ATPBH09', 'ATPDH58', 'WTA326735', 'ATPKC04', 'ATPTC01', 'WTA317070', 'ATPME82', 'ATPSL28', 'WTA319998', 'WTA323451', 'WTA325088', 'ATPF0F1', 'WTA322280', 'WTA325338', 'WTA322526', 'WTA315428', 'ATPCA12', 'WTA327909', 'ATPF724', 'WTA324267', 'ATPKD46', 'WTA318358', 'WTA321158', 'ATPGB93', 'WTA317938', 'ATPN771', 'WTA331330', 'ATPMP01', 'ATPCD85', 'ATPAG37', 'WTA322277', 'ATPM0HU', 'ATPK926', 'WTA320942', 'ATPPC11', 'WTA324479', 'WTA320408', 'WTA325826', 'WTA319112', 'WTA319436', 'ATPJ386', 'WTA324219', 'ATPE687', 'ATPN409', 'WTA315683', 'WTA312850', 'ATPTD51', 'WTA325320', 'WTA317510', 'WTA313169', 'WTA311593', 'ATPWB08', 'WTA321454', 'WTA322052', 'WTA326678', 'ATPD0CO', 'ATPSU55', 'WTA324934', 'ATPSH90', 'ATPI186', 'ATPKB05', 'WTA322942', 'WTA327241', 'ATPPG94', 'WTA322822', 'WTA320760', 'ATPL0BV', 'WTA319125', 'WTA326007', 'WTA327845', 'ATPRC91', 'WTA320682', 'WTA319969', 'WTA322191', 'WTA317771', 'ATPGA79', 'WTA318711', 'ATPS0GR', 'ATPMO44', 'WTA313975', 'ATPGC88', 'WTA319571', 'ATPZ419', 'ATPT786', 'ATPO449', 'WTA190787', 'ATPH0BH', 'WTA325601', 'ATPBI23', 'ATPDA81', 'WTA230234', 'WTA230220', 'ATPM0EJ', 'WTA190879', 'WTA316847', 'WTA318609', 'ATPP0HW', 'WTA320277', 'WTA318033', 'ATPV824', 'WTA327391', 'WTA324750', 'ATPTC61', 'WTA327077', 'WTA325410', 'WTA323027', 'WTA316266', 'WTA315130', 'ATPH996', 'WTA312584', 'WTA329090', 'ATPI230', 'ATPMF35', 'WTA312469', 'ATPN0AE', 'WTA320567', 'ATPBD80', 'WTA315295', 'ATPY268', 'ATPE831', 'WTA319939', 'WTA317421', 'ATPL575', 'WTA326384', 'ATPD994', 'ATPA678', 'ATPS0S1', 'WTA326653', 'ATPBF23', 'ATPB0GG', 'WTA315159', 'ATPBE90', 'ATPGF95', 'ATPS0RE', 'ATPL987', 'ATPD864', 'WTA330375', 'ATPBU13', 'ATPHH26', 'WTA310053', 'ATPKE64', 'WTA311137', 'WTA310331', 'ATPBD06', 'WTA321106', 'ATPBM95', 'WTA319696', 'ATPSD32', 'WTA320983', 'ATPLC12', 'ATPSX50', 'ATPD875', 'ATPCG04', 'WTA318872', 'WTA318176', 'WTA313974', 'ATPH997', 'WTA327196', 'WTA318494', 'WTA020702', 'ATPS0AG', 'ATPLB66', 'ATPSA93', 'ATPTE16', 'ATPMU94', 'WTA314320', 'WTA329199', 'WTA315391', 'ATPBG23', 'ATPGC89', 'WTA325956', 'ATPO522', 'ATPB0BI', 'WTA324261', 'ATPG858', 'WTA320926', 'ATPMM58', 'ATPDB63', 'WTA312268', 'WTA325836', 'ATPI305', 'ATPBT68', 'ATPC0AU', 'WTA324325', 'WTA318839', 'ATPPH71', 'ATPA0GC', 'ATPTA29', 'ATPL397', 'WTA313711', 'ATPSM37', 'WTA322214', 'WTA313987', 'WTA313907', 'WTA315997', 'ATPGB88', 'ATPT0AP', 'ATPS483', 'ATPF324', 'WTA260142', 'WTA328366', 'ATPV306', 'WTA320301', 'WTA317683', 'WTA312336', 'ATPK0AH', 'WTA311041', 'ATPHB64', 'ATPC0E9', 'ATPK0AZ', 'WTA317094', 'WTA331809', 'WTA329668', 'WTA322222', 'ATPA0E2', 'ATPGA94', 'ATPBI81', 'ATPN897', 'ATPBK92', 'WTA320013', 'WTA318312', 'WTA322082', 'WTA316738', 'WTA330482', 'ATPZ355', 'WTA329409', 'WTA328897', 'ATPV832', 'ATPMV14', 'ATPA829', 'ATPCE25', 'WTA328560', 'WTA318352', 'WTA316296', 'ATPM0OQ', 'ATPR0DG', 'WTA315365', 'WTA325936', 'WTA320316', 'ATPTE51', 'ATPK336', 'WTA110552', 'WTA316981', 'ATPJ551', 'WTA319709', 'ATPMM66', 'WTA318060', 'WTA313402', 'ATPM0FH', 'WTA327101', 'WTA330548', 'WTA317317', 'ATPFB98', 'WTA320735', 'ATPLB84', 'ATPB0CD', 'ATPMP20', 'WTA327367', 'ATPMC65', 'ATPC0H0', 'WTA314359', 'ATPO483', 'WTA319001', 'ATPL949', 'WTA326160', 'ATPC882', 'ATPDH50', 'WTA324576', 'ATPC0C8', 'WTA314206', 'WTA324702', 'WTA317790', 'WTA322087', 'WTA320319', 'ATPC0BC', 'ATPF510', 'ATPMH30', 'ATPGD64', 'WTA316739', 'WTA319473', 'WTA326482', 'ATPD874', 'ATPA596', 'ATPU134', 'ATPKI63', 'ATPDB59', 'ATPN552', 'WTA314917', 'ATPM0QI', 'ATPMK66', 'WTA316464', 'ATPCF59', 'WTA311338', 'WTA317065', 'ATPR772', 'WTA320716', 'ATPSL08', 'ATPTB69', 'ATPCG94', 'ATPHB71', 'WTA310761', 'ATPW09E', 'ATPD0CG', 'ATPSE73', 'WTA321179', 'ATPS0GD', 'ATPSK47', 'ATPKI82', 'ATPY218', 'ATPPD31', 'ATPVA70', 'WTA320238', 'WTA316239', 'ATPSK94', 'WTA316956', 'WTA326408', 'ATPP09Z', 'ATPSJ55', 'WTA326379', 'ATPMN13', 'WTA326096', 'WTA317684', 'ATPMC10', 'ATPA0FC', 'ATPN732', 'ATPKB09', 'WTA314237', 'ATPO513', 'ATPG09O'}
Unique player IDs from Roland Garros: {'29107', '37977', '38551', '2332', '45660', '21600', '30350', '31132', '38594', '37517', '37670', '43952', '31398', '22505', '17861', '32989', '31281', '15883', '31095', '43964', '9767', '4825', '7837', '15913', '19041', '22568', '31313', '28771', '35361', '19962', '39723', '18275', '28369', '14747', '11493', '40607', '26219', '32402', '26448', '44408', '43781', '40967', '33597', '18274', '33416', '35854', '36744', '41418', '7792', '35919', '43643', '44187', '27419', '18348', '23598', '33524', '35329', '12105', '27099', '38353', '28420', '21647', '21904', '28779', '23968', '13153', '26311', '26485', '25481', '43155', '15722', '45674', '35961', '18439', '40824', '24807', '34411', '13859', '21355', '30857', '31392', '40499', '24618', '26111', '21707', '15108', '42928', '42533', '24955', '13235', '35246', '33529', '14065', '31091', '17421', '30552', '17608', '18839', '20124', '19706', '21500', '26128', '18005', '21805', '19748', '33456', '26021', '24367', '18533', '29098', '33271', '35753', '19921', '44009', '35289', '37966', '28865', '28687', '36748', '9852', '26197', '43689', '42557', '40609', '17343', '28758', '18251', '26325', '26058', '6291', '14415', '27902', '28763', '21863', '28836', '15645', '32919', '20017', '39036', '12748', '31356', '27898', '38371', '45689', '42515', '44509', '33614', '17949', '25050', '30361', '33541', '9117', '40720', '29682', '35398', '19319', '31288', '44161', '49300', '36358', '26967', '28518', '36989', '24162', '26513', '40210', '33787', '32885', '6083', '33851', '42566', '28052', '33560', '33616', '21578', '17007', '31976', '47762', '23726', '13059', '5699', '33462', '32341', '18049', '7815', '34455', '21519', '27929', '24248', '26506', '28510', '16392', '36389', '20557', '13256', '13263', '8546', '26310', '25890', '21623', '20304', '11073', '22454', '10216', '11344', '44185', '5745', '36307', '28697', '24584', '36258', '17011', '29969', '40087', '27258', '9086', '19858', '26183', '9525', '38127', '41825', '41884', '24265', '9677', '9046', '21820', '29171', '18033', '38570', '40683', '24660', '29318', '26436', '42340', '40467', '16944', '16659', '40622', '36373', '38338', '19746', '31036', '42304', '41293', '18124', '45655', '19769', '28888', '24215', '38582', '43748', '23872', '28266', '34350', '40399', '38569', '41022', '26285', '37647', '42514', '2508', '40624', '15820', '33606', '30238', '26234', '26227', '26208', '31098', '33663', '31166', '22760', '38755', '11713', '28635', '36384', '33206', '27071', '42559', '17510', '19749', '21776', '35655', '40613', '29046', '21066', '31184', '23770', '34679', '34635', '28197', '48819', '38437', '13354', '47759', '40660', '17152', '24788', '31367', '29820', '26348', '28593', '43602', '31798', '36325', '31217', '3370', '9801', '47345', '32244', '9592', '30524', '36276', '21741', '35542', '33031', '30464', '36781', '38004', '21835', '42529', '21908', '30764', '33732', '24574', '23738', '33731', '21248', '26434', '7184', '23386', '37719', '40998', '30797', '19666', '40442', '38726', '38639', '11362', '40849', '43970', '25127', '42494', '24313', '40635', '44313', '36620', '14608', '33675', '33249', '7774', '29550', '19689', '36701', '33639', '28346', '29528', '32019', '13555', '42560', '18972', '14440', '28280', '24375', '21892', '15374', '30646', '42575', '37989', '24342', '32390', '35699', '11674', '31276', '28684', '12595', '32094'}

In [22]:
def create_players_csv(catalogue_df, players_csv_path):
    australian_open_ids = get_unique_player_ids(catalogue_df, 'australian_open')
    roland_garros_ids = get_unique_player_ids(catalogue_df, 'roland_garros')
    
    players_data = []

    for player_id_ao in australian_open_ids:
        player1_entry = catalogue_df[catalogue_df['player1_id'] == player_id_ao]
        player2_entry = catalogue_df[catalogue_df['player2_id'] == player_id_ao]

        # If player_entry is not empty, add player1 information
        if not player1_entry.empty:
            player1_entry = player1_entry.iloc[0]
            player_name = player1_entry['player1']
            surname = normalize_name(player_name)
            player_index = next((index for index, player in enumerate(players_data) if player['player_name'] == surname), None)
            if player_index is not None:
                players_data[player_index]['player_id_ao'] = player_id_ao
                players_data[player_index]['league'] = player1_entry['league']
            else:
                players_data.append({'player_name': surname, 'player_id_ao': player_id_ao, 'league': player1_entry['league']})

        if not player2_entry.empty:
            player2_entry = player2_entry.iloc[0]
            player_name = player2_entry['player2']
            surname = normalize_name(player_name)
            
            player_index = next((index for index, player in enumerate(players_data) if player['player_name'] == surname), None)
            if player_index is not None:
                players_data[player_index]['player_id_ao'] = player_id_ao
                players_data[player_index]['league'] = player2_entry['league']
            else:
                players_data.append({'player_name': surname, 'player_id_ao': player_id_ao, 'league': player2_entry['league']})

    for player_id_rg in roland_garros_ids:
        player1_entry = catalogue_df[catalogue_df['player1_id'] == player_id_rg]
        player2_entry = catalogue_df[catalogue_df['player2_id'] == player_id_rg]

        if not player1_entry.empty:
            player1_entry = player1_entry.iloc[0]
            player_name = player1_entry['player1']
            surname = normalize_name(player_name)
            
            player_index = next((index for index, player in enumerate(players_data) if player['player_name'] == surname), None)
            if player_index is not None:
                players_data[player_index]['player_id_rg'] = player_id_rg
                players_data[player_index]['league'] = player1_entry['league']
                players_data[player_index]['country'] = player1_entry['player1_country']
            else:
                # If player does not exist, add a new entry
                print("player1_entry", player1_entry)
                players_data.append({'player_name': surname, 'player_id_rg': int(player_id_rg), 'league': player1_entry['league'], 'country': player1_entry['player1_country']})

        if not player2_entry.empty:
            player2_entry = player2_entry.iloc[0]
            player_name = player2_entry['player2']
            surname = normalize_name(player_name)
            # Check if the player already exists in the list
            player_index = next((index for index, player in enumerate(players_data) if player['player_name'] == surname), None)
            if player_index is not None:
                # If player exists, update the entry with additional information
                players_data[player_index]['player_id_rg'] = player_id_rg
                players_data[player_index]['league'] = player2_entry['league']
                players_data[player_index]['country'] = player2_entry['player2_country']
            else:
                # If player does not exist, add a new entry
                players_data.append({'player_name': surname, 'player_id_rg': int(player_id_rg), 'league': player2_entry['league'], 'country': player2_entry['player2_country']})

    
    players_data = sorted(players_data, key=lambda x: x['player_name'])

    players_df = pd.DataFrame(players_data)

    players_df.to_csv(players_csv_path, index=False)

catalogue_path = "players_matches_catalogue/catalogue_all_matches_available.csv"
players_csv_path = "players.csv"
catalogue_df = pd.read_csv(catalogue_path)
create_players_csv(catalogue_df, players_csv_path)

player1_entry year                                   2020
player1                          K.ZAVATSKA
player2                           K.BERTENS
player1_id                            38594
player2_id                            17861
player1_country                         UKR
player2_country                         NED
player1_seed                            NaN
player2_seed                            5.0
court_name            Court Suzanne LENGLEN
court_id                                  2
num_sets_completed                        3
match_type                  Women's Singles
match_status                              C
match_id                              SD079
tournament                    roland_garros
league                                  wta
Name: 1727, dtype: object
player1_entry year                                     2019
player1                              M.KLIZAN
player2                             L.POUILLE
player1_id                              15883
player2_id                              26325
player1_country                           SVK
player2_country                           FRA
player1_seed                              NaN
player2_seed                             22.0
court_name            Court Philippe CHATRIER
court_id                                    1
num_sets_completed                          5
match_type                      Men's Singles
match_status                                C
match_id                                SM045
tournament                      roland_garros
league                                    atp
Name: 1288, dtype: object
player1_entry year                                     2021
player1                             D.ISTOMIN
player2                             R.FEDERER
player1_id                               7837
player2_id                               2508
player1_country                           UZB
player2_country                           SUI
player1_seed                              NaN
player2_seed                              8.0
court_name            Court Philippe CHATRIER
court_id                                    1
num_sets_completed                          3
match_type                      Men's Singles
match_status                                C
match_id                                SM079
tournament                      roland_garros
league                                    atp
Name: 1402, dtype: object
player1_entry year                             2022
player1                      C.MONNET
player2                     K.MUCHOVA
player1_id                      43781
player2_id                      35961
player1_country                   FRA
player2_country                   CZE
player1_seed                      NaN
player2_seed                      NaN
court_name                    Court 7
court_id                            9
num_sets_completed                  2
match_type            Women's Singles
match_status                        C
match_id                        SD110
tournament              roland_garros
league                            wta
Name: 1892, dtype: object
player1_entry year                                   2020
player1                              J.SOCK
player2                             D.THIEM
player1_id                            25481
player2_id                            26348
player1_country                         USA
player2_country                         AUT
player1_seed                            NaN
player2_seed                            3.0
court_name            Court Suzanne LENGLEN
court_id                                  2
num_sets_completed                        3
match_type                    Men's Singles
match_status                              C
match_id                              SM055
tournament                    roland_garros
league                                  atp
Name: 1333, dtype: object
player1_entry year                           2022
player1                      B.GOJO
player2                F.KRAJINOVIC
player1_id                    34411
player2_id                    20557
player1_country                 CRO
player2_country                 SRB
player1_seed                    NaN
player2_seed                    NaN
court_name                 Court 12
court_id                         14
num_sets_completed                4
match_type            Men's Singles
match_status                      C
match_id                      SM037
tournament            roland_garros
league                          atp
Name: 1450, dtype: object
player1_entry year                                2022
player1               V.GRAMMATIKOPOULOU
player2                        D.SAVILLE
player1_id                         30552
player2_id                         21805
player1_country                      GRE
player2_country                      AUS
player1_seed                         NaN
player2_seed                         NaN
court_name                       Court 9
court_id                              11
num_sets_completed                     2
match_type               Women's Singles
match_status                           C
match_id                           SD098
tournament                 roland_garros
league                               wta
Name: 1880, dtype: object
player1_entry year                                   2019
player1                             Y.MADEN
player2                             R.NADAL
player1_id                            17608
player2_id                             7792
player1_country                         GER
player2_country                         ESP
player1_seed                            NaN
player2_seed                            2.0
court_name            Court Suzanne LENGLEN
court_id                                  2
num_sets_completed                        3
match_type                    Men's Singles
match_status                              C
match_id                              SM063
tournament                    roland_garros
league                                  atp
Name: 1292, dtype: object
player1_entry year                           2022
player1                 A.GIANNESSI
player2                      B.GOJO
player1_id                    18839
player2_id                    34411
player1_country                 ITA
player2_country                 CRO
player1_seed                    NaN
player2_seed                    NaN
court_name                  Court 4
court_id                          6
num_sets_completed                5
match_type            Men's Singles
match_status                      C
match_id                      SM074
tournament            roland_garros
league                          atp
Name: 1477, dtype: object
player1_entry year                           2022
player1                 A.KUZNETSOV
player2               D.SCHWARTZMAN
player1_id                    19748
player2_id                    24162
player1_country                 ---
player2_country                 ARG
player1_seed                    NaN
player2_seed                   15.0
court_name                  Court 6
court_id                          8
num_sets_completed                4
match_type            Men's Singles
match_status                      C
match_id                      SM071
tournament            roland_garros
league                          atp
Name: 1474, dtype: object
player1_entry year                                   2023
player1                       I.SHYMANOVICH
player2                         A.SABALENKA
player1_id                            33271
player2_id                            33249
player1_country                         ---
player2_country                         ---
player1_seed                            NaN
player2_seed                            2.0
court_name            Court Suzanne-LENGLEN
court_id                                  2
num_sets_completed                        2
match_type                  Women's Singles
match_status                              C
match_id                              SD063
tournament                    roland_garros
league                                  wta
Name: 1947, dtype: object
player1_entry year                             2022
player1                    A.GASANOVA
player2                    M.BOUZKOVA
player1_id                      35753
player2_id                      31217
player1_country                   ---
player2_country                   CZE
player1_seed                      NaN
player2_seed                      NaN
court_name                    Court 6
court_id                            8
num_sets_completed                  2
match_type            Women's Singles
match_status                        C
match_id                        SD114
tournament              roland_garros
league                            wta
Name: 1896, dtype: object
player1_entry year                             2022
player1                   M.BJORKLUND
player2                       D.VEKIC
player1_id                      37966
player2_id                      26513
player1_country                   SWE
player2_country                   CRO
player1_seed                      NaN
player2_seed                      NaN
court_name                    Court 8
court_id                           10
num_sets_completed                  2
match_type            Women's Singles
match_status                        C
match_id                        SD109
tournament              roland_garros
league                            wta
Name: 1891, dtype: object
player1_entry year                             2024
player1                   E.JACQUEMOT
player2                      A.BOGDAN
player1_id                      43689
player2_id                      19858
player1_country                   FRA
player2_country                   ROU
player1_seed                      NaN
player2_seed                      NaN
court_name                    Court 7
court_id                            9
num_sets_completed                  2
match_type            Women's Singles
match_status                        C
match_id                        SD106
tournament              roland_garros
league                            wta
Name: 2019, dtype: object
player1_entry year                             2022
player1                    R.SRAMKOVA
player2                   D.KASATKINA
player1_id                      31356
player2_id                      31281
player1_country                   SVK
player2_country                   ---
player1_seed                      NaN
player2_seed                     20.0
court_name                    Court 8
court_id                           10
num_sets_completed                  2
match_type            Women's Singles
match_status                        C
match_id                        SD091
tournament              roland_garros
league                            wta
Name: 1873, dtype: object
player1_entry year                                     2024
player1                       F.MELIGENIALVES
player2                                C.RUUD
player1_id                              38371
player2_id                              36389
player1_country                           BRA
player2_country                           NOR
player1_seed                              NaN
player2_seed                              7.0
court_name            Court Philippe-CHATRIER
court_id                                    1
num_sets_completed                          2
match_type                      Men's Singles
match_status                                I
match_id                                SM079
tournament                      roland_garros
league                                    atp
Name: 1636, dtype: object
player1_entry year                                     2024
player1                            E.ANDREEVA
player2                           A.SABALENKA
player1_id                              45689
player2_id                              33249
player1_country                           ---
player2_country                           ---
player1_seed                              NaN
player2_seed                              2.0
court_name            Court Philippe-CHATRIER
court_id                                    1
num_sets_completed                          2
match_type                    Women's Singles
match_status                                C
match_id                                SD127
tournament                      roland_garros
league                                    wta
Name: 2026, dtype: object
player1_entry year                                     2021
player1                               O.BABEL
player2                           E.SVITOLINA
player1_id                              44509
player2_id                              23968
player1_country                           FRA
player2_country                           UKR
player1_seed                              NaN
player2_seed                              5.0
court_name            Court Philippe CHATRIER
court_id                                    1
num_sets_completed                          1
match_type                    Women's Singles
match_status                                I
match_id                                SD079
tournament                      roland_garros
league                                    wta
Name: 1784, dtype: object
player1_entry year                           2024
player1                     L.NARDI
player2                    A.MULLER
player1_id                    44161
player2_id                    32341
player1_country                 ITA
player2_country                 FRA
player1_seed                    NaN
player2_seed                    NaN
court_name                  Court 7
court_id                          9
num_sets_completed                3
match_type            Men's Singles
match_status                      C
match_id                      SM098
tournament            roland_garros
league                          atp
Name: 1644, dtype: object
player1_entry year                                   2019
player1                           S.BOLELLI
player2                           L.POUILLE
player1_id                             9677
player2_id                            26325
player1_country                         ITA
player2_country                         FRA
player1_seed                            NaN
player2_seed                           22.0
court_name            Court Suzanne LENGLEN
court_id                                  2
num_sets_completed                        3
match_type                    Men's Singles
match_status                              C
match_id                              SM091
tournament                    roland_garros
league                                  atp
Name: 1297, dtype: object
player1_entry year                                 2022
player1               SF.RODRIGUEZTAVERNA
player2                           T.FRITZ
player1_id                          37647
player2_id                          34350
player1_country                       ARG
player2_country                       USA
player1_seed                          NaN
player2_seed                         13.0
court_name                        Court 6
court_id                                8
num_sets_completed                      5
match_type                  Men's Singles
match_status                            C
match_id                            SM087
tournament                  roland_garros
league                                atp
Name: 1490, dtype: object
player1_entry year                                   2021
player1                            ES.LIANG
player2                             F.FERRO
player1_id                            42514
player2_id                            30524
player1_country                         TPE
player2_country                         FRA
player1_seed                            NaN
player2_seed                            NaN
court_name            Court Suzanne LENGLEN
court_id                                  2
num_sets_completed                        2
match_type                  Women's Singles
match_status                              I
match_id                              SD070
tournament                    roland_garros
league                                  wta
Name: 1781, dtype: object
player1_entry year                                   2022
player1                  T.ANDRIANJAFITRIMO
player2                         KA.PLISKOVA
player1_id                            33606
player2_id                            18274
player1_country                         FRA
player2_country                         CZE
player1_seed                            NaN
player2_seed                            8.0
court_name            Court Simonne MATHIEU
court_id                                  3
num_sets_completed                        3
match_type                  Women's Singles
match_status                              C
match_id                              SD079
tournament                    roland_garros
league                                  wta
Name: 1861, dtype: object
player1_entry year                           2022
player1                B.FRATANGELO
player2                    J.SINNER
player1_id                    26234
player2_id                    39723
player1_country                 USA
player2_country                 ITA
player1_seed                    NaN
player2_seed                   11.0
court_name                  Court 7
court_id                          9
num_sets_completed                3
match_type            Men's Singles
match_status                      C
match_id                      SM119
tournament            roland_garros
league                          atp
Name: 1522, dtype: object
player1_entry year                           2021
player1                   M.BOURGUE
player2                   D.KOEPFER
player1_id                    26208
player2_id                    32094
player1_country                 FRA
player2_country                 GER
player1_seed                    NaN
player2_seed                    NaN
court_name                  Court 6
court_id                          8
num_sets_completed                3
match_type            Men's Singles
match_status                      C
match_id                      SM077
tournament            roland_garros
league                          atp
Name: 1400, dtype: object
player1_entry year                                   2020
player1                          J.RODIONOV
player2                            J.CHARDY
player1_id                            36384
player2_id                            11493
player1_country                         AUT
player2_country                         FRA
player1_seed                            NaN
player2_seed                            NaN
court_name            Court Suzanne LENGLEN
court_id                                  2
num_sets_completed                        5
match_type                    Men's Singles
match_status                              C
match_id                              SM101
tournament                    roland_garros
league                                  atp
Name: 1343, dtype: object
player1_entry year                                     2019
player1                               A.HOANG
player2                             G.MONFILS
player1_id                              27071
player2_id                               9525
player1_country                           FRA
player2_country                           FRA
player1_seed                              NaN
player2_seed                             14.0
court_name            Court Philippe CHATRIER
court_id                                    1
num_sets_completed                          3
match_type                      Men's Singles
match_status                                C
match_id                                SM021
tournament                      roland_garros

In [23]:
players_csv_path = "players.csv"
player_df = pd.read_csv(players_csv_path)
player_df.head()

   player_name player_id_ao league  player_id_rg country
0  A.ANISIMOVA    WTA326384    wta       40607.0     USA
1     A.BALAZS      ATPBD80    atp       15374.0     HUN
2      A.BARTY    WTA318033    wta       27902.0     AUS
3     A.BEDENE      ATPBH09    atp       19666.0     SLO
4   A.BLINKOVA    WTA324267    wta       33614.0     RUS

In [24]:
players_csv_path = "players.csv"
player_df = pd.read_csv(players_csv_path)

player_df['player_id_rg'] = player_df['player_id_rg'].fillna(0)
player_df['player_id_rg'] = player_df['player_id_rg'].astype(int)

if 'player_id_ao' in player_df.columns:
    player_df['player_id_atp'] = player_df['player_id_ao'].str.replace('ATP', '', 1).str.replace('WTA', '', 1)

player_df.to_csv(players_csv_path, index=False)

saved_player_df = pd.read_csv(players_csv_path)
print("Updated DataFrame saved to " + players_csv_path)
print(saved_player_df)

Updated DataFrame saved to players.csv
             player_name player_id_ao league  player_id_rg country  \
0            A.ANISIMOVA    WTA326384    wta         40607     USA
1               A.BALAZS      ATPBD80    atp         15374     HUN
2                A.BARTY    WTA318033    wta         27902     AUS
3               A.BEDENE      ATPBH09    atp         19666     SLO
4             A.BLINKOVA    WTA324267    wta         33614     RUS
5               A.BOGDAN    WTA315427    wta         19858     ROU
6              A.BOLSOVA    WTA320735    wta             0     NaN
7                 A.BOLT      ATPBI81    atp             0     NaN
8               A.BONDAR    WTA322942    wta         33616     HUN
9               A.BUBLIK      ATPBK92    atp         29098     KAZ
10              A.CAZAUX      ATPC0H0    atp         43952     FRA
11              A.CORNET    WTA312121    wta         13263     FRA
12    A.DAVIDOVICHFOKINA      ATPDH50    atp         39036     ESP
13            A.DEMINAUR      ATPDH58    atp         36276     AUS
14                A.FILS      ATPF0F1    atp         47762     FRA
15            A.GASANOVA          NaN    wta         35753     ---
16           A.GIANNESSI          NaN    atp         18839     ITA
17              A.HARRIS      ATPHB29    atp             0     NaN
18             A.HARTONO    WTA323451    wta             0     NaN
19               A.HOANG          NaN    atp         27071     FRA
20            A.KALININA    WTA320567    wta         31276     UKR
21          A.KALINSKAYA    WTA323942    wta         33663     ---
22            A.KARATSEV      ATPKC56    atp         24955     ---
23              A.KERBER    WTA311470    wta         11344     GER
24              A.KONJUH    WTA320682    wta         31288     CRO
25           A.KONTAVEIT    WTA318425    wta         26434     EST
26            A.KORNEEVA    WTA331330    wta             0     NaN
27           A.KOVACEVIC      ATPK0AZ    atp         41293     USA
28             A.KRUEGER    WTA329409    wta             0     NaN
29              A.KRUNIC    WTA316344    wta         21835     SRB
30           A.KUZNETSOV          NaN    atp         19748     ---
31                  A.LI    WTA326096    wta         40660     USA
32             A.LOTTNER    WTA318494    wta             0     NaN
33           A.MANNARINO      ATPME82    atp         13859     FRA
34              A.MARTIN      ATPMF35    atp             0     NaN
35           A.MICHELSEN      ATPM0QI    atp         49300     USA
36              A.MOLCAN      ATPMV14    atp         33524     SVK
37              A.MULLER      ATPMP20    atp         32341     FRA
38              A.MURRAY      ATPMC10    atp         10216     GBR
39               A.PARKS    WTA326007    wta             0     NaN
40      A.PAVLYUCHENKOVA    WTA313796    wta         15108     RUS
41            A.PETKOVIC    WTA310770    wta          9046     GER
42             A.POPYRIN      ATPP09Z    atp         36373     AUS
43            A.POTAPOVA    WTA325601    wta         38726     RUS
44       A.RAMOS-VINOLAS      ATPR772    atp         14065     ESP
45         A.RINDERKNECH      ATPRC91    atp         29969     FRA
46               A.RISKE    WTA312850    wta         14747     USA
47           A.RODIONOVA    WTA312413    wta             0     NaN
48              A.RUBLEV      ATPRE44    atp         31132     RUS
49                 A.RUS    WTA313349    wta         17152     NED
50           A.SABALENKA    WTA320760    wta         33249     BLR
51           A.SASNOVICH    WTA317790    wta         26058     BLR
52         A.SCHMIEDLOVA    WTA318203    wta         26485     SVK
53               A.SEPPI      ATPSA93    atp             0     NaN
54           A.SEVASTOVA    WTA313987    wta         18348     LAT
55              A.SHARMA    WTA319696    wta         30857     AUS
56          A.SHEVCHENKO      ATPS0H2    atp         42494     ---
57              A.TABILO      ATPTE30    atp             0     NaN
58         A.TOMLJANOVIC    WTA315232    wta         19962     AUS
59         A.VANUYTVANCK    WTA317819    wta         26128     BEL
60               A.VUKIC      ATPV832    atp             0     NaN
61              A.WALTON      ATPW09E    atp             0     NaN
62           A.ZAKHAROVA    WTA327367    wta             0     NaN
63              A.ZVEREV      ATPZ355    atp         30350     GER
64           B.ANDREESCU    WTA325088    wta         38570     CAN
65              B.BENCIC    WTA319001    wta         28865     SUI
66               B.BONZI      ATPBM95    atp         33416     FRA
67               B.CORIC      ATPCG80    atp         29171     CRO
68          B.FRATANGELO          NaN    atp         26234     USA
69         B.FRUHVIRTOVA    WTA331545    wta         47759     CZE
70                B.GOJO          NaN    atp         34411     CRO
71          B.HADDADMAIA    WTA318176    wta         28052     BRA
72                B.HOLT      ATPH09P    atp             0     NaN
73          B.KREJCIKOVA    WTA318314    wta         26436     CZE
74           B.NAKASHIMA      ATPN0AE    atp         41418     USA
75               B.PAIRE      ATPPD31    atp         20017     FRA
76                B.PERA    WTA317708    wta         28763     USA
77             B.SHELTON      ATPS0S1    atp         47345     USA
78            B.STRYCOVA    WTA190879    wta             0     NaN
79               B.TOMIC      ATPTA46    atp             0     NaN
80     B.VANDEZANDSCHULP      ATPV812    atp         30238     NED
81      B.ZAPATAMIRALLES      ATPZ419    atp         35542     ESP
82             C.ALCARAZ      ATPA0E2    atp         44408     ESP
83              C.BELLIS    WTA322526    wta             0     NaN
84               C.BUCSA    WTA321158    wta         35655     ESP
85               C.BUREL    WTA325320    wta         41884     FRA
86            C.DOLEHIDE    WTA322052    wta             0     NaN
87             C.EUBANKS      ATPE865    atp         31798     USA
88              C.GARCIA    WTA315391    wta         23726     FRA
89               C.GARIN      ATPGD64    atp         26967     CHI
90               C.GAUFF    WTA328560    wta         44185     USA
91              C.GIORGI    WTA314610    wta         18005     ITA
92           C.LESTIENNE      ATPLB66    atp         25050     FRA
93                 C.LIU    WTA323966    wta         38127     USA
94              C.MCHALE    WTA314917    wta             0     NaN
95             C.MCNALLY    WTA325725    wta             0     NaN
96              C.MONNET          NaN    wta         43781     FRA
97              C.MOUTET      ATPMW02    atp         36358     FRA
98              C.NORRIE      ATPN771    atp         28593     GBR
99           C.O'CONNELL      ATPO483    atp         29820     AUS
100             C.OSORIO    WTA325898    wta         40720     COL
101             C.PAQUET    WTA318839    wta         28266     FRA
102               C.RUUD      ATPRH16    atp         36389     NOR
103              C.STEBE      ATPSK94    atp             0     NaN
104      C.SUAREZNAVARRO    WTA311338    wta         11073     ESP
105           C.TABERNER      ATPTE16    atp         35329     ESP
106             C.TAUSON    WTA327793    wta         42533     DEN
107              C.TSENG      ATPT0AP    atp         40467     TPE
108       C.UGOCARABELLI          NaN    atp         38437     ARG
109         C.VANDEWEGHE    WTA314464    wta             0     NaN
110          C.WOZNIACKI    WTA313402    wta         13256     DEN
111              D.AIAVA    WTA324219    wta             0     NaN
112           D.ALTMAIER      ATPAE14    atp         33851     GER
113            D.COLLINS    WTA316925    wta         30464     USA
114            D.DZUMHUR      ATPD923    atp             0     NaN
115              D.EVANS      ATPE687    atp         15645     GBR
116              D.GALAN      ATPGE33    atp         29318     COL
117              D.GALFI    WTA321106    wta         33639     HUN
118          D.GAVRILOVA    WTA315997    wta             0     NaN
119             D.GOFFIN      ATPGB88    atp         19706     BEL
120            D.ISTOMIN          NaN    atp          7837     UZB
121          D.KASATKINA    WTA322082    wta         31281     ---
122            D.KOEPFER      ATPKE73    atp         32094     GER
123            D.KOVINIC    WTA317684    wta         25890     MNE
124              D.KUDLA      ATPKB09    atp         19746     USA
125            D.LAJOVIC      ATPL987    atp         19749     SRB
126           D.MEDVEDEV      ATPMM58    atp         28836     RUS
127              D.NOVAK      ATPDB59    atp         26311     AUT
128              D.PARRY    WTA327077    wta         40849     FRA
129            D.PRIZMIC      ATPP0HW    atp             0     NaN
130            D.SAVILLE    WTA315997    wta         21805     AUS
131        D.SCHWARTZMAN      ATPSM37    atp         24162     ARG
132         D.SHAPOVALOV      ATPSU55    atp         35246     CAN
133           D.SHNAIDER    WTA330482    wta         45655     ---
134             D.SNIGUR    WTA327845    wta             0     NaN
135            D.SVRCINA      ATPS0GD    atp             0     NaN
136             D.SWEENY      ATPS0IA    atp             0     NaN
137              D.THIEM      ATPTB69    atp         26348     AUT
138              D.VEKIC    WTA318516    wta         26513     CRO
139         D.YASTREMSKA    WTA324261    wta         38338     UKR
140        E.ALEXANDROVA    WTA319007    wta         30361     RUS
141           E.ANDREEVA          NaN    wta         45689     ---
142          E.AVANESYAN    WTA327620    wta         42559     ---
143             E.BEKTAS    WTA316464    wta             0     NaN
144         E.BENCHETRIT      ATPBT68    atp         36744     FRA
145           E.BOUCHARD          NaN    wta         21776     CAN
146        E.COCCIARETTO    WTA327909    wta         43602     ITA
147           E.COUACAUD      ATPCG94    atp         28510     FRA
148            E.DONSKOY      ATPD864    atp             0     NaN
149           E.ESCOBEDO      ATPE873    atp             0     NaN
150          E.GERASIMOV      ATPGC89    atp         24788     BLR
151              E.GOMEZ      ATPGA36    atp             0     NaN
152             E.GULBIS      ATPG858    atp             0     NaN
153          E.JACQUEMOT          NaN    wta         43689     FRA
154                E.LYS    WTA325826    wta         43748     GER
155            E.MANDLIK    WTA326379    wta             0     NaN
156            E.MERTENS    WTA317964    wta         26448     BEL
157            E.NAVARRO    WTA325410    wta         40210     USA
158           E.RADUCANU    WTA328366    wta         42575     GBR
159             E.RODINA    WTA312584    wta         13235     RUS
160               E.RUSE    WTA320408    wta             0     NaN
161         E.RUUSUVUORI      ATPRH24    atp         37670     FIN
162           E.RYBAKINA    WTA324166    wta         38569     KAZ
163             E.SEIDEL    WTA330548    wta             0     NaN
164          E.SVITOLINA    WTA316738    wta         23968     UKR
165            E.VESNINA          NaN    wta          9117     RUS
166               E.YMER      ATPY218    atp         31184     SWE
167              EG.RUSE          NaN    wta         33731     ROU
168             ES.LIANG          NaN    wta         42514     TPE
169          F.AGAMENONE          NaN    atp         24375     ITA
170     F.AUGERALIASSIME      ATPAG37    atp         36701     CAN
171             F.BAGNIS      ATPBF23    atp         18533     ARG
172          F.CERUNDOLO      ATPC0AU    atp         40998     ARG
173            F.COBOLLI      ATPC0E9    atp         42928     ITA
174     F.CONTRERASGOMEZ          NaN    wta         38004     MEX
175              F.CORIA      ATPCE77    atp         24618     ARG
176           F.DELBONIS      ATPD874    atp         20304     ARG
177         F.DIAZACOSTA      ATPD0CG    atp             0     NaN
178      F.FERREIRASILVA      ATPSN54    atp             0     NaN
179              F.FERRO    WTA319969    wta         30524     FRA
180            F.FOGNINI      ATPF510    atp          9852     ITA
181              F.JONES    WTA324479    wta             0     NaN
182         F.KRAJINOVIC      ATPKB05    atp         20557     SRB
183              F.LOPEZ      ATPL397    atp             0     NaN
184           F.MAROZSAN      ATPM0CI    atp             0     NaN
185      F.MELIGENIALVES          NaN    atp         38371     BRA
186             F.TIAFOE      ATPTD51    atp         35361     USA
187           F.VERDASCO      ATPV306    atp             0     NaN
188            G.BARRERE      ATPBK24    atp         26197     FRA
189        G.BLANCANEAUX          NaN    atp         36258     FRA
190           G.DIMITROV      ATPD875    atp         19689     BUL
191              G.MAGER      ATPML57    atp         27258     ITA
192             G.MINNEN    WTA321454    wta         31313     BEL
193            G.MONFILS      ATPMC65    atp          9525     FRA
194           G.MUGURUZA    WTA316239    wta         23872     ESP
195              G.PELLA      ATPPC11    atp             0     NaN
196              G.SIMON      ATPSD32    atp          7774     FRA
197           G.ZEPPIERI      ATPZ0A1    atp         41825     ITA
198          GA.OLIVIERI          NaN    atp         37517     ARG
199           H.BAPTISTE    WTA327101    wta         42515     USA
200               H.DART    WTA319489    wta         28684     GBR
201            H.DELLIEN      ATPDA31    atp         24660     BOL
202             H.GASTON      ATPG09O    atp         38551     FRA
203            H.GRENIER      ATPGF95    atp             0     NaN
204            H.HURKACZ      ATPHB71    atp         31976     POL
205          H.LAAKSONEN      ATPL949    atp         19041     SUI
206               H.RUNE      ATPR0DG    atp         43970     DEN
207                H.TAN    WTA320016    wta         31398     FRA
208             H.WATSON    WTA316981    wta         21904     GBR
209               I.BARA    WTA318352    wta         27898     ROU
210               I.BEGU    WTA313169    wta         16659     ROU
211            I.IVASHKA      ATPI305    atp         27099     ---
212           I.KARLOVIC      ATPK336    atp             0     NaN
213        I.SHYMANOVICH          NaN    wta         33271     ---
214            I.SWIATEK    WTA326408    wta         40613     POL
215            J.AVDEEVA          NaN    wta         44313     ---
216              J.BRADY    WTA318358    wta         27929     USA
217           J.BROOKSBY      ATPB0CD    atp         40967     USA
218            J.BURRAGE    WTA323802    wta             0     NaN
219          J.CERUNDOLO      ATPC0C8    atp             0     NaN
220             J.CHARDY      ATPCA12    atp         11493     FRA
221           J.CRISTIAN    WTA320319    wta         32989     ROU
222             J.DEJONG      ATPD0C1    atp         42304     NED
223           J.DELPOTRO          NaN    atp         11713     ARG
224             J.DRAPER      ATPD0CO    atp             0     NaN
225          J.DUCKWORTH      ATPD994    atp         21600     AUS
226            J.FOURLIS    WTA322822    wta             0     NaN
227            J.GOERGES    WTA313381    wta             0     NaN
228            J.GRABHER    WTA320316    wta         28697     AUT
229              J.ISNER      ATPI186    atp         15820     USA
230              J.KONTA    WTA313907    wta         16944     GBR
231            J.KOVALIK      ATPKC04    atp         21647     SVK
232             J.KUBLER      ATPKB95    atp         22760     AUS
233            J.LARSSON    WTA311593    wta         12748     SWE
234            J.LEHECKA      ATPL0BV    atp         43155     CZE
235            J.LONDERO      ATPLB84    atp         26285     ARG
236             J.MCCABE      ATPM0OQ    atp             0     NaN
237             J.MENSIK      ATPM0NI    atp             0     NaN
238            J.MILLMAN      ATPMH30    atp         19769     AUS
239              J.MUNAR      ATPMU94    atp         33529     ESP
240           J.NIEMEIER    WTA325940    wta         40624     GER
241          J.OSTAPENKO    WTA319939    wta         28758     LAT
242            J.PAOLINI    WTA319280    wta         33206     ITA
243             J.PEGULA    WTA316956    wta         21863     USA
244           J.RODIONOV          NaN    atp         36384     AUT
245              J.SHANG      ATPS0RE    atp             0     NaN
246             J.SINNER      ATPS0AG    atp         39723     ITA
247              J.SMITH      ATPSJ55    atp             0     NaN
248               J.SOCK          NaN    atp         25481     USA
249              J.SOUSA      ATPSH90    atp         16392     POR
250             J.STRUFF      ATPSL28    atp         23386     GER
251          J.TEICHMANN    WTA320926    wta         31367     SUI
252           J.THOMPSON      ATPTC61    atp         28635     AUS
253             J.TSONGA      ATPT786    atp          6291     FRA
254           J.VARILLAS      ATPV836    atp         31166     PER
255             J.VESELY      ATPV708    atp         21741     CZE
256               J.WOLF      ATPW09G    atp         40399     USA
257                K.AHN    WTA316159    wta         23598     USA
258           K.ANDERSON      ATPA678    atp             0     NaN
259             K.BAINDL    WTA316739    wta             0     NaN
260            K.BERTENS    WTA314584    wta         17861     NED
261            K.BIRRELL    WTA320728    wta             0     NaN
262         K.BONDARENKO    WTA020702    wta             0     NaN
263            K.BOULTER    WTA319125    wta             0     NaN
264          K.COPPEJANS      ATPCG33    atp             0     NaN
265                K.DAY    WTA322534    wta         35699     USA
266             K.EDMUND      ATPE831    atp             0     NaN
267           K.FLIPKENS    WTA310331    wta             0     NaN
268              K.JUVAN    WTA324702    wta         40087     SLO
269             K.KANEPI    WTA110536    wta          5699     EST
270          K.KHACHANOV      ATPKE29    atp         29528     RUS
271            K.KOZLOVA    WTA316739    wta             0     NaN
272             K.KUCOVA    WTA312673    wta         14608     SVK
273          K.MAJCHRZAK      ATPMQ75    atp         31091     POL
274         K.MLADENOVIC    WTA315616    wta         19921     FRA
275            K.MUCHOVA    WTA322191    wta         35961     CZE
276               K.NARA          NaN    wta         17421     JPN
277          K.NISHIKORI      ATPN552    atp         13059     JPN
278           K.PLISKOVA    WTA313974    wta             0     NaN
279          K.RAKHIMOVA    WTA325936    wta         40622     ---
280              K.SEBOV    WTA322214    wta             0     NaN
281          K.SINIAKOVA    WTA320301    wta         28779     CZE
282           K.VOLYNETS    WTA327391    wta         42557     USA
283           K.ZAVATSKA          NaN    wta         38594     UKR
284          KA.PLISKOVA    WTA313974    wta         18274     CZE
285          KR.PLISKOVA    WTA313975    wta         18275     CZE
286             L.BROADY      ATPBI23    atp             0     NaN
287          L.BRONZETTI    WTA322280    wta         37977     ITA
288            L.CABRERA    WTA320013    wta             0     NaN
289              L.DAVIS    WTA317414    wta             0     NaN
290              L.DJERE      ATPDB63    atp         28518     SRB
291          L.FERNANDEZ    WTA326735    wta         43643     CAN
292        L.FRUHVIRTOVA    WTA329627    wta             0     NaN
293           L.GIUSTINO      ATPGA79    atp             0     NaN
294             L.HARRIS      ATPHG86    atp         33462     RSA
295           L.JEANJEAN    WTA320313    wta         24367     FRA

### Fixes players.csv

In [25]:
league = 'atp'


players_info = get_all_players_info('', league)
players_info_df = get_all_players_info_df('', league)

print(players_info_df)
players_with_miss_id = players_info_df['player_name'][players_info_df['player_id_atp'].isna()]

# atp_ids = [player_info[0].replace('ATP', '', 1) for player_info in players_info if player_info[0] != '']
players_with_miss_id = np.array(players_with_miss_id)

player_name A.BALAZS
player_id 15374
player_name A.BEDENE
player_id 19666
player_name A.BOLT
player_id 0
player_name A.BUBLIK
player_id 29098
player_name A.CAZAUX
player_id 43952
player_name A.DAVIDOVICHFOKINA
player_id 39036
player_name A.DEMINAUR
player_id 36276
player_name A.FILS
player_id 47762
player_name A.GIANNESSI
player_id 18839
player_name A.HARRIS
player_id 0
player_name A.HOANG
player_id 27071
player_name A.KARATSEV
player_id 24955
player_name A.KOVACEVIC
player_id 41293
player_name A.KUZNETSOV
player_id 19748
player_name A.MANNARINO
player_id 13859
player_name A.MARTIN
player_id 0
player_name A.MICHELSEN
player_id 49300
player_name A.MOLCAN
player_id 33524
player_name A.MULLER
player_id 32341
player_name A.MURRAY
player_id 10216
player_name A.POPYRIN
player_id 36373
player_name A.RAMOS-VINOLAS
player_id 14065
player_name A.RINDERKNECH
player_id 29969
player_name A.RUBLEV
player_id 31132
player_name A.SEPPI
player_id 0
player_name A.SHEVCHENKO
player_id 42494
player_name A.TABILO
player_id 0
player_name A.VUKIC
player_id 0
player_name A.WALTON
player_id 0
player_name A.ZVEREV
player_id 30350
player_name B.BONZI
player_id 33416
player_name B.CORIC
player_id 29171
player_name B.FRATANGELO
player_id 26234
player_name B.GOJO
player_id 34411
player_name B.HOLT
player_id 0
player_name B.NAKASHIMA
player_id 41418
player_name B.PAIRE
player_id 20017
player_name B.SHELTON
player_id 47345
player_name B.TOMIC
player_id 0
player_name B.VANDEZANDSCHULP
player_id 30238
player_name B.ZAPATAMIRALLES
player_id 35542
player_name C.ALCARAZ
player_id 44408
player_name C.EUBANKS
player_id 31798
player_name C.GARIN
player_id 26967
player_name C.LESTIENNE
player_id 25050
player_name C.MOUTET
player_id 36358
player_name C.NORRIE
player_id 28593
player_name C.O'CONNELL
player_id 29820
player_name C.RUUD
player_id 36389
player_name C.STEBE
player_id 0
player_name C.TABERNER
player_id 35329
player_name C.TSENG
player_id 40467
player_name C.UGOCARABELLI
player_id 38437
player_name D.ALTMAIER
player_id 33851
player_name D.DZUMHUR
player_id 0
player_name D.EVANS
player_id 15645
player_name D.GALAN
player_id 29318
player_name D.GOFFIN
player_id 19706
player_name D.ISTOMIN
player_id 7837
player_name D.KOEPFER
player_id 32094
player_name D.KUDLA
player_id 19746
player_name D.LAJOVIC
player_id 19749
player_name D.MEDVEDEV
player_id 28836
player_name D.NOVAK
player_id 26311
player_name D.PRIZMIC
player_id 0
player_name D.SCHWARTZMAN
player_id 24162
player_name D.SHAPOVALOV
player_id 35246
player_name D.SVRCINA
player_id 0
player_name D.SWEENY
player_id 0
player_name D.THIEM
player_id 26348
player_name E.BENCHETRIT
player_id 36744
player_name E.COUACAUD
player_id 28510
player_name E.DONSKOY
player_id 0
player_name E.ESCOBEDO
player_id 0
player_name E.GERASIMOV
player_id 24788
player_name E.GOMEZ
player_id 0
player_name E.GULBIS
player_id 0
player_name E.RUUSUVUORI
player_id 37670
player_name E.YMER
player_id 31184
player_name F.AGAMENONE
player_id 24375
player_name F.AUGERALIASSIME
player_id 36701
player_name F.BAGNIS
player_id 18533
player_name F.CERUNDOLO
player_id 40998
player_name F.COBOLLI
player_id 42928
player_name F.CORIA
player_id 24618
player_name F.DELBONIS
player_id 20304
player_name F.DIAZACOSTA
player_id 0
player_name F.FERREIRASILVA
player_id 0
player_name F.FOGNINI
player_id 9852
player_name F.KRAJINOVIC
player_id 20557
player_name F.LOPEZ
player_id 0
player_name F.MAROZSAN
player_id 0
player_name F.MELIGENIALVES
player_id 38371
player_name F.TIAFOE
player_id 35361
player_name F.VERDASCO
player_id 0
player_name G.BARRERE
player_id 26197
player_name G.BLANCANEAUX
player_id 36258
player_name G.DIMITROV
player_id 19689
player_name G.MAGER
player_id 27258
player_name G.MONFILS
player_id 9525
player_name G.PELLA
player_id 0
player_name G.SIMON
player_id 7774
player_name G.ZEPPIERI
player_id 41825
player_name GA.OLIVIERI
player_id 37517
player_name H.DELLIEN
player_id 24660
player_name H.GASTON
player_id 38551
player_name H.GRENIER
player_id 0
player_name H.HURKACZ
player_id 31976
player_name H.LAAKSONEN
player_id 19041
player_name H.RUNE
player_id 43970
player_name I.IVASHKA
player_id 27099
player_name I.KARLOVIC
player_id 0
player_name J.BROOKSBY
player_id 40967
player_name J.CERUNDOLO
player_id 0
player_name J.CHARDY
player_id 11493
player_name J.DEJONG
player_id 42304
player_name J.DELPOTRO
player_id 11713
player_name J.DRAPER
player_id 0
player_name J.DUCKWORTH
player_id 21600
player_name J.ISNER
player_id 15820
player_name J.KOVALIK
player_id 21647
player_name J.KUBLER
player_id 22760
player_name J.LEHECKA
player_id 43155
player_name J.LONDERO
player_id 26285
player_name J.MCCABE
player_id 0
player_name J.MENSIK
player_id 0
player_name J.MILLMAN
player_id 19769
player_name J.MUNAR
player_id 33529
player_name J.RODIONOV
player_id 36384
player_name J.SHANG
player_id 0
player_name J.SINNER
player_id 39723
player_name J.SMITH
player_id 0
player_name J.SOCK
player_id 25481
player_name J.SOUSA
player_id 16392
player_name J.STRUFF
player_id 23386
player_name J.THOMPSON
player_id 28635
player_name J.TSONGA
player_id 6291
player_name J.VARILLAS
player_id 31166
player_name J.VESELY
player_id 21741
player_name J.WOLF
player_id 40399
player_name K.ANDERSON
player_id 0
player_name K.COPPEJANS
player_id 0
player_name K.EDMUND
player_id 0
player_name K.KHACHANOV
player_id 29528
player_name K.MAJCHRZAK
player_id 31091
player_name K.NISHIKORI
player_id 13059
player_name L.BROADY
player_id 0
player_name L.DJERE
player_id 28518
player_name L.GIUSTINO
player_id 0
player_name L.HARRIS
player_id 33462
player_name L.KLEIN
player_id 0
player_name L.LOKOLI
player_id 0
player_name L.MAYER
player_id 12105
player_name L.MUSETTI
player_id 42340
player_name L.NARDI
player_id 44161
player_name L.POUILLE
player_id 26325
player_name L.SONEGO
player_id 35289
player_name L.TU
player_id 0
player_name L.VANASSCHE
player_id 0
player_name M.ARNALDI
player_id 43964
player_name M.BELLUCCI
player_id 0
player_name M.BERRETTINI
player_id 29046
player_name M.BOURGUE
player_id 26208
player_name M.CECCHINATO
player_id 24584
player_name M.CILIC
player_id 11674
player_name M.CRESSY
player_id 41022
player_name M.FUCSOVICS
player_id 22454
player_name M.GIRON
player_id 24807
player_name M.GUINARD
player_id 34455
player_name M.HUESLER
player_id 0
player_name M.KECMANOVIC
player_id 38353
player_name M.KLIZAN
player_id 15883
player_name M.KUKUSHKIN
player_id 15913
player_name M.MARTERER
player_id 29682
player_name M.MCDONALD
player_id 25127
player_name M.MMOH
player_id 31095
player_name M.POLMANS
player_id 0
player_name M.PURCELL
player_id 0
player_name M.RAONIC
player_id 0
player_name M.SAFWAT
player_id 0
player_name M.TORPEGAARD
player_id 0
player_name M.TRUNGELLITI
player_id 0
player_name M.VALKUSZ
player_id 0
player_name M.VILELLAMARTINEZ
player_id 0
player_name M.YMER
player_id 33597
player_name N.BASILASHVILI
player_id 20124
player_name N.BORGES
player_id 36781
player_name N.DJOKOVIC
player_id 9801
player_name N.GOMBOS
player_id 22505
player_name N.JARRY
player_id 32019
player_name N.KYRGIOS
player_id 0
player_name N.MILOJEVIC
player_id 0
player_name O.JASIKA
player_id 0
player_name O.KRUTYKH
player_id 0
player_name O.OTTE
player_id 27419
player_name P.ANDUJAR
player_id 9592
player_name P.CACHIN
player_id 29107
player_name P.CARRENOBUSTA
player_id 21578
player_name P.CUEVAS
player_id 9767
player_name P.GOJOWCZYK
player_id 15722
player_name P.GUNNESWARAN
player_id 0
player_name P.HERBERT
player_id 21623
player_name P.KOHLSCHREIBER
player_id 4825
player_name P.KOTOV
player_id 36325
player_name P.KYPSON
player_id 0
player_name P.MARTINEZ
player_id 32244
player_name P.SOUSA
player_id 0
player_name Q.HALYS
player_id 31036
player_name R.ALBOT
player_id 0
player_name R.BAUTISTAAGUT
player_id 13354
player_name R.BERANKIS
player_id 17510
player_name R.CARBALLESBAENA
player_id 26219
player_name R.FEDERER
player_id 2508
player_name R.GASQUET
player_id 6083
player_name R.HAASE
player_id 0
player_name R.HIJIKATA
player_id 0
player_name R.NADAL
player_id 7792
player_name R.OPELKA
player_id 32402
player_name R.SAFIULLIN
player_id 33560
player_name S.BAEZ
player_id 40442
player_name S.BOLELLI
player_id 9677
player_name S.CARUSO
player_id 24574
player_name S.JOHNSON
player_id 18972
player_name S.KORDA
player_id 40824
player_name S.KOZLOV
player_id 0
player_name S.KWON
player_id 34679
player_name S.MOCHIZUKI
player_id 44009
player_name S.NAGAL
player_id 31098
player_name S.OFNER
player_id 32390
player_name S.QUERREY
player_id 0
player_name S.STAKHOVSKY
player_id 0
player_name S.TRAVAGLIA
player_id 21066
player_name S.TSITSIPAS
player_id 35398
player_name S.WAWRINKA
player_id 7815
player_name SF.RODRIGUEZTAVERNA
player_id 37647
player_name T.ATMANE
player_id 0
player_name T.BARRIOSVERA
player_id 0
player_name T.DANIEL
player_id 26227
player_name T.ETCHEVERRY
player_id 36989
player_name T.FABBIANO
player_id 13555
player_name T.FRITZ
player_id 34350
player_name T.GRIEKSPOOR
player_id 33456
player_name T.ITO
player_id 0
player_name T.KOKKINAKIS
player_id 29550
player_name T.MACHAC
player_id 40499
player_name T.MONTEIRO
player_id 0
player_name T.PAUL
player_id 33541
player_name T.SANDGREN
player_id 21707
player_name T.SEYBOTHWILD
player_id 37719
player_name T.SKATOV
player_id 0
player_name U.HUMBERT
player_id 36307
player_name V.KOPRIVA
player_id 0
player_name V.POSPISIL
player_id 19319
player_name V.TROICKI
player_id 0
player_name Y.HANFMANN
player_id 22568
player_name Y.HSU
player_id 0
player_name Y.LU
player_id 0
player_name Y.MADEN
player_id 17608
player_name Y.NISHIOKA
player_id 26310
player_name Y.SUGITA
player_id 0
player_name Y.UCHIYAMA
player_id 0
player_name Y.WATANUKI
player_id 0
player_name Y.WU
player_id 0
player_name Z.BERGS
player_id 36748
player_name Z.KOLAR
player_id 34635
player_name Z.ZHANG
player_id 32885
             player_name player_id_ao league  player_id_rg country  \
1               A.BALAZS      ATPBD80    atp         15374     HUN
3               A.BEDENE      ATPBH09    atp         19666     SLO
7                 A.BOLT      ATPBI81    atp             0     NaN
9               A.BUBLIK      ATPBK92    atp         29098     KAZ
10              A.CAZAUX      ATPC0H0    atp         43952     FRA
12    A.DAVIDOVICHFOKINA      ATPDH50    atp         39036     ESP
13            A.DEMINAUR      ATPDH58    atp         36276     AUS
14                A.FILS      ATPF0F1    atp         47762     FRA
16           A.GIANNESSI          NaN    atp         18839     ITA
17              A.HARRIS      ATPHB29    atp             0     NaN
19               A.HOANG          NaN    atp         27071     FRA
22            A.KARATSEV      ATPKC56    atp         24955     ---
27           A.KOVACEVIC      ATPK0AZ    atp         41293     USA
30           A.KUZNETSOV          NaN    atp         19748     ---
33           A.MANNARINO      ATPME82    atp         13859     FRA
34              A.MARTIN      ATPMF35    atp             0     NaN
35           A.MICHELSEN      ATPM0QI    atp         49300     USA
36              A.MOLCAN      ATPMV14    atp         33524     SVK
37              A.MULLER      ATPMP20    atp         32341     FRA
38              A.MURRAY      ATPMC10    atp         10216     GBR
42             A.POPYRIN      ATPP09Z    atp         36373     AUS
44       A.RAMOS-VINOLAS      ATPR772    atp         14065     ESP
45         A.RINDERKNECH      ATPRC91    atp         29969     FRA
48              A.RUBLEV      ATPRE44    atp         31132     RUS
53               A.SEPPI      ATPSA93    atp             0     NaN
56          A.SHEVCHENKO      ATPS0H2    atp         42494     ---
57              A.TABILO      ATPTE30    atp             0     NaN
60               A.VUKIC      ATPV832    atp             0     NaN
61              A.WALTON      ATPW09E    atp             0     NaN
63              A.ZVEREV      ATPZ355    atp         30350     GER
66               B.BONZI      ATPBM95    atp         33416     FRA
67               B.CORIC      ATPCG80    atp         29171     CRO
68          B.FRATANGELO          NaN    atp         26234     USA
70                B.GOJO          NaN    atp         34411     CRO
72                B.HOLT      ATPH09P    atp             0     NaN
74           B.NAKASHIMA      ATPN0AE    atp         41418     USA
75               B.PAIRE      ATPPD31    atp         20017     FRA
77             B.SHELTON      ATPS0S1    atp         47345     USA
79               B.TOMIC      ATPTA46    atp             0     NaN
80     B.VANDEZANDSCHULP      ATPV812    atp         30238     NED
81      B.ZAPATAMIRALLES      ATPZ419    atp         35542     ESP
82             C.ALCARAZ      ATPA0E2    atp         44408     ESP
87             C.EUBANKS      ATPE865    atp         31798     USA
89               C.GARIN      ATPGD64    atp         26967     CHI
92           C.LESTIENNE      ATPLB66    atp         25050     FRA
97              C.MOUTET      ATPMW02    atp         36358     FRA
98              C.NORRIE      ATPN771    atp         28593     GBR
99           C.O'CONNELL      ATPO483    atp         29820     AUS
102               C.RUUD      ATPRH16    atp         36389     NOR
103              C.STEBE      ATPSK94    atp             0     NaN
105           C.TABERNER      ATPTE16    atp         35329     ESP
107              C.TSENG      ATPT0AP    atp         40467     TPE
108       C.UGOCARABELLI          NaN    atp         38437     ARG
112           D.ALTMAIER      ATPAE14    atp         33851     GER
114            D.DZUMHUR      ATPD923    atp             0     NaN
115              D.EVANS      ATPE687    atp         15645     GBR
116              D.GALAN      ATPGE33    atp         29318     COL
119             D.GOFFIN      ATPGB88    atp         19706     BEL
120            D.ISTOMIN          NaN    atp          7837     UZB
122            D.KOEPFER      ATPKE73    atp         32094     GER
124              D.KUDLA      ATPKB09    atp         19746     USA
125            D.LAJOVIC      ATPL987    atp         19749     SRB
126           D.MEDVEDEV      ATPMM58    atp         28836     RUS
127              D.NOVAK      ATPDB59    atp         26311     AUT
129            D.PRIZMIC      ATPP0HW    atp             0     NaN
131        D.SCHWARTZMAN      ATPSM37    atp         24162     ARG
132         D.SHAPOVALOV      ATPSU55    atp         35246     CAN
135            D.SVRCINA      ATPS0GD    atp             0     NaN
136             D.SWEENY      ATPS0IA    atp             0     NaN
137              D.THIEM      ATPTB69    atp         26348     AUT
144         E.BENCHETRIT      ATPBT68    atp         36744     FRA
147           E.COUACAUD      ATPCG94    atp         28510     FRA
148            E.DONSKOY      ATPD864    atp             0     NaN
149           E.ESCOBEDO      ATPE873    atp             0     NaN
150          E.GERASIMOV      ATPGC89    atp         24788     BLR
151              E.GOMEZ      ATPGA36    atp             0     NaN
152             E.GULBIS      ATPG858    atp             0     NaN
161         E.RUUSUVUORI      ATPRH24    atp         37670     FIN
166               E.YMER      ATPY218    atp         31184     SWE
169          F.AGAMENONE          NaN    atp         24375     ITA
170     F.AUGERALIASSIME      ATPAG37    atp         36701     CAN
171             F.BAGNIS      ATPBF23    atp         18533     ARG
172          F.CERUNDOLO      ATPC0AU    atp         40998     ARG
173            F.COBOLLI      ATPC0E9    atp         42928     ITA
175              F.CORIA      ATPCE77    atp         24618     ARG
176           F.DELBONIS      ATPD874    atp         20304     ARG
177         F.DIAZACOSTA      ATPD0CG    atp             0     NaN
178      F.FERREIRASILVA      ATPSN54    atp             0     NaN
180            F.FOGNINI      ATPF510    atp          9852     ITA
182         F.KRAJINOVIC      ATPKB05    atp         20557     SRB
183              F.LOPEZ      ATPL397    atp             0     NaN
184           F.MAROZSAN      ATPM0CI    atp             0     NaN
185      F.MELIGENIALVES          NaN    atp         38371     BRA
186             F.TIAFOE      ATPTD51    atp         35361     USA
187           F.VERDASCO      ATPV306    atp             0     NaN
188            G.BARRERE      ATPBK24    atp         26197     FRA
189        G.BLANCANEAUX          NaN    atp         36258     FRA
190           G.DIMITROV      ATPD875    atp         19689     BUL
191              G.MAGER      ATPML57    atp         27258     ITA
193            G.MONFILS      ATPMC65    atp          9525     FRA
195              G.PELLA      ATPPC11    atp             0     NaN
196              G.SIMON      ATPSD32    atp          7774     FRA
197           G.ZEPPIERI      ATPZ0A1    atp         41825     ITA
198          GA.OLIVIERI          NaN    atp         37517     ARG
201            H.DELLIEN      ATPDA31    atp         24660     BOL
202             H.GASTON      ATPG09O    atp         38551     FRA
203            H.GRENIER      ATPGF95    atp             0     NaN
204            H.HURKACZ      ATPHB71    atp         31976     POL
205          H.LAAKSONEN      ATPL949    atp         19041     SUI
206               H.RUNE      ATPR0DG    atp         43970     DEN
211            I.IVASHKA      ATPI305    atp         27099     ---
212           I.KARLOVIC      ATPK336    atp             0     NaN
217           J.BROOKSBY      ATPB0CD    atp         40967     USA
219          J.CERUNDOLO      ATPC0C8    atp             0     NaN
220             J.CHARDY      ATPCA12    atp         11493     FRA
222             J.DEJONG      ATPD0C1    atp         42304     NED
223           J.DELPOTRO          NaN    atp         11713     ARG
224             J.DRAPER      ATPD0CO    atp             0     NaN
225          J.DUCKWORTH      ATPD994    atp         21600     AUS
229              J.ISNER      ATPI186    atp         15820     USA
231            J.KOVALIK      ATPKC04    atp         21647     SVK
232             J.KUBLER      ATPKB95    atp         22760     AUS
234            J.LEHECKA      ATPL0BV    atp         43155     CZE
235            J.LONDERO      ATPLB84    atp         26285     ARG
236             J.MCCABE      ATPM0OQ    atp             0     NaN
237             J.MENSIK      ATPM0NI    atp             0     NaN
238            J.MILLMAN      ATPMH30    atp         19769     AUS
239              J.MUNAR      ATPMU94    atp         33529     ESP
244           J.RODIONOV          NaN    atp         36384     AUT
245              J.SHANG      ATPS0RE    atp             0     NaN
246             J.SINNER      ATPS0AG    atp         39723     ITA
247              J.SMITH      ATPSJ55    atp             0     NaN
248               J.SOCK          NaN    atp         25481     USA
249              J.SOUSA      ATPSH90    atp         16392     POR
250             J.STRUFF      ATPSL28    atp         23386     GER
252           J.THOMPSON      ATPTC61    atp         28635     AUS
253             J.TSONGA      ATPT786    atp          6291     FRA
254           J.VARILLAS      ATPV836    atp         31166     PER
255             J.VESELY      ATPV708    atp         21741     CZE
256               J.WOLF      ATPW09G    atp         40399     USA
258           K.ANDERSON      ATPA678    atp             0     NaN
264          K.COPPEJANS      ATPCG33    atp             0     NaN
266             K.EDMUND      ATPE831    atp             0     NaN
270          K.KHACHANOV      ATPKE29    atp         29528     RUS
273          K.MAJCHRZAK      ATPMQ75    atp         31091     POL
277          K.NISHIKORI      ATPN552    atp         13059     JPN
286             L.BROADY      ATPBI23    atp             0     NaN
290              L.DJERE      ATPDB63    atp         28518     SRB
293           L.GIUSTINO      ATPGA79    atp             0     NaN
294             L.HARRIS      ATPHG86    atp         33462     RSA

In [26]:
players_with_miss_id

array(['A.GIANNESSI', 'A.HOANG', 'A.KUZNETSOV', 'B.FRATANGELO', 'B.GOJO',
       'C.UGOCARABELLI', 'D.ISTOMIN', 'F.AGAMENONE', 'F.MELIGENIALVES',
       'G.BLANCANEAUX', 'GA.OLIVIERI', 'J.DELPOTRO', 'J.RODIONOV',
       'J.SOCK', 'L.NARDI', 'M.BOURGUE', 'M.GUINARD', 'M.KLIZAN',
       'S.BOLELLI', 'SF.RODRIGUEZTAVERNA', 'T.FABBIANO', 'Y.MADEN',
       'Z.KOLAR'], dtype=object)

In [27]:
players_csv_path = "players.csv"
players_df = pd.read_csv(players_csv_path)

player_ids_missing = {
    "A.GIANNESSI": "G983",
    "A.HOANG": "HA71",
    "A.KUZNETSOV": "KB54",
    "B.FRATANGELO": "F811",
    "B.GOJO": "GH92",
    "C.UGOCARABELLI": "U182",
    "CH.TSENG": "T0AP",
    "D.ISTOMIN": "I165",
    "F.AGAMENONE": "AA27",
    "G.BLANCANEAUX": "BU54",
    "GA.OLIVIERI": "O660",
    "J.DELPOTRO": "D683",
    "J.RODIONOV": "R09X",
    "J.SOCK": "SM25",
    "JP.VARILLAS": "V836",
    "M.BOURGUE": "BK19",
    "M.GUINARD": "GH33",
    "M.KLIZAN": "K966",
    "S.BOLELLI": "BA98",
    "SF.RODRIGUEZTAVERNA": "RH59",
    "T.FABBIANO": "F586",
    "TM.ETCHEVERRY": "EA24",
    "Y.MADEN": "MH16",
    "Z.KOLAR": "KH56",
    "F.MELIGENIALVES": "MW75",
    "L.NARDI": "N0BG"
}

for player_name, player_id in player_ids_missing.items():
    players_df.loc[players_df["player_name"] == player_name, "player_id_atp"] = player_id

players_df.to_csv(players_csv_path, index=False)

saved_players_df = pd.read_csv(players_csv_path)
print("Updated DataFrame saved to " + players_csv_path)
print(saved_players_df)

Updated DataFrame saved to players.csv
             player_name player_id_ao league  player_id_rg country  \
0            A.ANISIMOVA    WTA326384    wta         40607     USA
1               A.BALAZS      ATPBD80    atp         15374     HUN
2                A.BARTY    WTA318033    wta         27902     AUS
3               A.BEDENE      ATPBH09    atp         19666     SLO
4             A.BLINKOVA    WTA324267    wta         33614     RUS
5               A.BOGDAN    WTA315427    wta         19858     ROU
6              A.BOLSOVA    WTA320735    wta             0     NaN
7                 A.BOLT      ATPBI81    atp             0     NaN
8               A.BONDAR    WTA322942    wta         33616     HUN
9               A.BUBLIK      ATPBK92    atp         29098     KAZ
10              A.CAZAUX      ATPC0H0    atp         43952     FRA
11              A.CORNET    WTA312121    wta         13263     FRA
12    A.DAVIDOVICHFOKINA      ATPDH50    atp         39036     ESP
13            A.DEMINAUR      ATPDH58    atp         36276     AUS
14                A.FILS      ATPF0F1    atp         47762     FRA
15            A.GASANOVA          NaN    wta         35753     ---
16           A.GIANNESSI          NaN    atp         18839     ITA
17              A.HARRIS      ATPHB29    atp             0     NaN
18             A.HARTONO    WTA323451    wta             0     NaN
19               A.HOANG          NaN    atp         27071     FRA
20            A.KALININA    WTA320567    wta         31276     UKR
21          A.KALINSKAYA    WTA323942    wta         33663     ---
22            A.KARATSEV      ATPKC56    atp         24955     ---
23              A.KERBER    WTA311470    wta         11344     GER
24              A.KONJUH    WTA320682    wta         31288     CRO
25           A.KONTAVEIT    WTA318425    wta         26434     EST
26            A.KORNEEVA    WTA331330    wta             0     NaN
27           A.KOVACEVIC      ATPK0AZ    atp         41293     USA
28             A.KRUEGER    WTA329409    wta             0     NaN
29              A.KRUNIC    WTA316344    wta         21835     SRB
30           A.KUZNETSOV          NaN    atp         19748     ---
31                  A.LI    WTA326096    wta         40660     USA
32             A.LOTTNER    WTA318494    wta             0     NaN
33           A.MANNARINO      ATPME82    atp         13859     FRA
34              A.MARTIN      ATPMF35    atp             0     NaN
35           A.MICHELSEN      ATPM0QI    atp         49300     USA
36              A.MOLCAN      ATPMV14    atp         33524     SVK
37              A.MULLER      ATPMP20    atp         32341     FRA
38              A.MURRAY      ATPMC10    atp         10216     GBR
39               A.PARKS    WTA326007    wta             0     NaN
40      A.PAVLYUCHENKOVA    WTA313796    wta         15108     RUS
41            A.PETKOVIC    WTA310770    wta          9046     GER
42             A.POPYRIN      ATPP09Z    atp         36373     AUS
43            A.POTAPOVA    WTA325601    wta         38726     RUS
44       A.RAMOS-VINOLAS      ATPR772    atp         14065     ESP
45         A.RINDERKNECH      ATPRC91    atp         29969     FRA
46               A.RISKE    WTA312850    wta         14747     USA
47           A.RODIONOVA    WTA312413    wta             0     NaN
48              A.RUBLEV      ATPRE44    atp         31132     RUS
49                 A.RUS    WTA313349    wta         17152     NED
50           A.SABALENKA    WTA320760    wta         33249     BLR
51           A.SASNOVICH    WTA317790    wta         26058     BLR
52         A.SCHMIEDLOVA    WTA318203    wta         26485     SVK
53               A.SEPPI      ATPSA93    atp             0     NaN
54           A.SEVASTOVA    WTA313987    wta         18348     LAT
55              A.SHARMA    WTA319696    wta         30857     AUS
56          A.SHEVCHENKO      ATPS0H2    atp         42494     ---
57              A.TABILO      ATPTE30    atp             0     NaN
58         A.TOMLJANOVIC    WTA315232    wta         19962     AUS
59         A.VANUYTVANCK    WTA317819    wta         26128     BEL
60               A.VUKIC      ATPV832    atp             0     NaN
61              A.WALTON      ATPW09E    atp             0     NaN
62           A.ZAKHAROVA    WTA327367    wta             0     NaN
63              A.ZVEREV      ATPZ355    atp         30350     GER
64           B.ANDREESCU    WTA325088    wta         38570     CAN
65              B.BENCIC    WTA319001    wta         28865     SUI
66               B.BONZI      ATPBM95    atp         33416     FRA
67               B.CORIC      ATPCG80    atp         29171     CRO
68          B.FRATANGELO          NaN    atp         26234     USA
69         B.FRUHVIRTOVA    WTA331545    wta         47759     CZE
70                B.GOJO          NaN    atp         34411     CRO
71          B.HADDADMAIA    WTA318176    wta         28052     BRA
72                B.HOLT      ATPH09P    atp             0     NaN
73          B.KREJCIKOVA    WTA318314    wta         26436     CZE
74           B.NAKASHIMA      ATPN0AE    atp         41418     USA
75               B.PAIRE      ATPPD31    atp         20017     FRA
76                B.PERA    WTA317708    wta         28763     USA
77             B.SHELTON      ATPS0S1    atp         47345     USA
78            B.STRYCOVA    WTA190879    wta             0     NaN
79               B.TOMIC      ATPTA46    atp             0     NaN
80     B.VANDEZANDSCHULP      ATPV812    atp         30238     NED
81      B.ZAPATAMIRALLES      ATPZ419    atp         35542     ESP
82             C.ALCARAZ      ATPA0E2    atp         44408     ESP
83              C.BELLIS    WTA322526    wta             0     NaN
84               C.BUCSA    WTA321158    wta         35655     ESP
85               C.BUREL    WTA325320    wta         41884     FRA
86            C.DOLEHIDE    WTA322052    wta             0     NaN
87             C.EUBANKS      ATPE865    atp         31798     USA
88              C.GARCIA    WTA315391    wta         23726     FRA
89               C.GARIN      ATPGD64    atp         26967     CHI
90               C.GAUFF    WTA328560    wta         44185     USA
91              C.GIORGI    WTA314610    wta         18005     ITA
92           C.LESTIENNE      ATPLB66    atp         25050     FRA
93                 C.LIU    WTA323966    wta         38127     USA
94              C.MCHALE    WTA314917    wta             0     NaN
95             C.MCNALLY    WTA325725    wta             0     NaN
96              C.MONNET          NaN    wta         43781     FRA
97              C.MOUTET      ATPMW02    atp         36358     FRA
98              C.NORRIE      ATPN771    atp         28593     GBR
99           C.O'CONNELL      ATPO483    atp         29820     AUS
100             C.OSORIO    WTA325898    wta         40720     COL
101             C.PAQUET    WTA318839    wta         28266     FRA
102               C.RUUD      ATPRH16    atp         36389     NOR
103              C.STEBE      ATPSK94    atp             0     NaN
104      C.SUAREZNAVARRO    WTA311338    wta         11073     ESP
105           C.TABERNER      ATPTE16    atp         35329     ESP
106             C.TAUSON    WTA327793    wta         42533     DEN
107              C.TSENG      ATPT0AP    atp         40467     TPE
108       C.UGOCARABELLI          NaN    atp         38437     ARG
109         C.VANDEWEGHE    WTA314464    wta             0     NaN
110          C.WOZNIACKI    WTA313402    wta         13256     DEN
111              D.AIAVA    WTA324219    wta             0     NaN
112           D.ALTMAIER      ATPAE14    atp         33851     GER
113            D.COLLINS    WTA316925    wta         30464     USA
114            D.DZUMHUR      ATPD923    atp             0     NaN
115              D.EVANS      ATPE687    atp         15645     GBR
116              D.GALAN      ATPGE33    atp         29318     COL
117              D.GALFI    WTA321106    wta         33639     HUN
118          D.GAVRILOVA    WTA315997    wta             0     NaN
119             D.GOFFIN      ATPGB88    atp         19706     BEL
120            D.ISTOMIN          NaN    atp          7837     UZB
121          D.KASATKINA    WTA322082    wta         31281     ---
122            D.KOEPFER      ATPKE73    atp         32094     GER
123            D.KOVINIC    WTA317684    wta         25890     MNE
124              D.KUDLA      ATPKB09    atp         19746     USA
125            D.LAJOVIC      ATPL987    atp         19749     SRB
126           D.MEDVEDEV      ATPMM58    atp         28836     RUS
127              D.NOVAK      ATPDB59    atp         26311     AUT
128              D.PARRY    WTA327077    wta         40849     FRA
129            D.PRIZMIC      ATPP0HW    atp             0     NaN
130            D.SAVILLE    WTA315997    wta         21805     AUS
131        D.SCHWARTZMAN      ATPSM37    atp         24162     ARG
132         D.SHAPOVALOV      ATPSU55    atp         35246     CAN
133           D.SHNAIDER    WTA330482    wta         45655     ---
134             D.SNIGUR    WTA327845    wta             0     NaN
135            D.SVRCINA      ATPS0GD    atp             0     NaN
136             D.SWEENY      ATPS0IA    atp             0     NaN
137              D.THIEM      ATPTB69    atp         26348     AUT
138              D.VEKIC    WTA318516    wta         26513     CRO
139         D.YASTREMSKA    WTA324261    wta         38338     UKR
140        E.ALEXANDROVA    WTA319007    wta         30361     RUS
141           E.ANDREEVA          NaN    wta         45689     ---
142          E.AVANESYAN    WTA327620    wta         42559     ---
143             E.BEKTAS    WTA316464    wta             0     NaN
144         E.BENCHETRIT      ATPBT68    atp         36744     FRA
145           E.BOUCHARD          NaN    wta         21776     CAN
146        E.COCCIARETTO    WTA327909    wta         43602     ITA
147           E.COUACAUD      ATPCG94    atp         28510     FRA
148            E.DONSKOY      ATPD864    atp             0     NaN
149           E.ESCOBEDO      ATPE873    atp             0     NaN
150          E.GERASIMOV      ATPGC89    atp         24788     BLR
151              E.GOMEZ      ATPGA36    atp             0     NaN
152             E.GULBIS      ATPG858    atp             0     NaN
153          E.JACQUEMOT          NaN    wta         43689     FRA
154                E.LYS    WTA325826    wta         43748     GER
155            E.MANDLIK    WTA326379    wta             0     NaN
156            E.MERTENS    WTA317964    wta         26448     BEL
157            E.NAVARRO    WTA325410    wta         40210     USA
158           E.RADUCANU    WTA328366    wta         42575     GBR
159             E.RODINA    WTA312584    wta         13235     RUS
160               E.RUSE    WTA320408    wta             0     NaN
161         E.RUUSUVUORI      ATPRH24    atp         37670     FIN
162           E.RYBAKINA    WTA324166    wta         38569     KAZ
163             E.SEIDEL    WTA330548    wta             0     NaN
164          E.SVITOLINA    WTA316738    wta         23968     UKR
165            E.VESNINA          NaN    wta          9117     RUS
166               E.YMER      ATPY218    atp         31184     SWE
167              EG.RUSE          NaN    wta         33731     ROU
168             ES.LIANG          NaN    wta         42514     TPE
169          F.AGAMENONE          NaN    atp         24375     ITA
170     F.AUGERALIASSIME      ATPAG37    atp         36701     CAN
171             F.BAGNIS      ATPBF23    atp         18533     ARG
172          F.CERUNDOLO      ATPC0AU    atp         40998     ARG
173            F.COBOLLI      ATPC0E9    atp         42928     ITA
174     F.CONTRERASGOMEZ          NaN    wta         38004     MEX
175              F.CORIA      ATPCE77    atp         24618     ARG
176           F.DELBONIS      ATPD874    atp         20304     ARG
177         F.DIAZACOSTA      ATPD0CG    atp             0     NaN
178      F.FERREIRASILVA      ATPSN54    atp             0     NaN
179              F.FERRO    WTA319969    wta         30524     FRA
180            F.FOGNINI      ATPF510    atp          9852     ITA
181              F.JONES    WTA324479    wta             0     NaN
182         F.KRAJINOVIC      ATPKB05    atp         20557     SRB
183              F.LOPEZ      ATPL397    atp             0     NaN
184           F.MAROZSAN      ATPM0CI    atp             0     NaN
185      F.MELIGENIALVES          NaN    atp         38371     BRA
186             F.TIAFOE      ATPTD51    atp         35361     USA
187           F.VERDASCO      ATPV306    atp             0     NaN
188            G.BARRERE      ATPBK24    atp         26197     FRA
189        G.BLANCANEAUX          NaN    atp         36258     FRA
190           G.DIMITROV      ATPD875    atp         19689     BUL
191              G.MAGER      ATPML57    atp         27258     ITA
192             G.MINNEN    WTA321454    wta         31313     BEL
193            G.MONFILS      ATPMC65    atp          9525     FRA
194           G.MUGURUZA    WTA316239    wta         23872     ESP
195              G.PELLA      ATPPC11    atp             0     NaN
196              G.SIMON      ATPSD32    atp          7774     FRA
197           G.ZEPPIERI      ATPZ0A1    atp         41825     ITA
198          GA.OLIVIERI          NaN    atp         37517     ARG
199           H.BAPTISTE    WTA327101    wta         42515     USA
200               H.DART    WTA319489    wta         28684     GBR
201            H.DELLIEN      ATPDA31    atp         24660     BOL
202             H.GASTON      ATPG09O    atp         38551     FRA
203            H.GRENIER      ATPGF95    atp             0     NaN
204            H.HURKACZ      ATPHB71    atp         31976     POL
205          H.LAAKSONEN      ATPL949    atp         19041     SUI
206               H.RUNE      ATPR0DG    atp         43970     DEN
207                H.TAN    WTA320016    wta         31398     FRA
208             H.WATSON    WTA316981    wta         21904     GBR
209               I.BARA    WTA318352    wta         27898     ROU
210               I.BEGU    WTA313169    wta         16659     ROU
211            I.IVASHKA      ATPI305    atp         27099     ---
212           I.KARLOVIC      ATPK336    atp             0     NaN
213        I.SHYMANOVICH          NaN    wta         33271     ---
214            I.SWIATEK    WTA326408    wta         40613     POL
215            J.AVDEEVA          NaN    wta         44313     ---
216              J.BRADY    WTA318358    wta         27929     USA
217           J.BROOKSBY      ATPB0CD    atp         40967     USA
218            J.BURRAGE    WTA323802    wta             0     NaN
219          J.CERUNDOLO      ATPC0C8    atp             0     NaN
220             J.CHARDY      ATPCA12    atp         11493     FRA
221           J.CRISTIAN    WTA320319    wta         32989     ROU
222             J.DEJONG      ATPD0C1    atp         42304     NED
223           J.DELPOTRO          NaN    atp         11713     ARG
224             J.DRAPER      ATPD0CO    atp             0     NaN
225          J.DUCKWORTH      ATPD994    atp         21600     AUS
226            J.FOURLIS    WTA322822    wta             0     NaN
227            J.GOERGES    WTA313381    wta             0     NaN
228            J.GRABHER    WTA320316    wta         28697     AUT
229              J.ISNER      ATPI186    atp         15820     USA
230              J.KONTA    WTA313907    wta         16944     GBR
231            J.KOVALIK      ATPKC04    atp         21647     SVK
232             J.KUBLER      ATPKB95    atp         22760     AUS
233            J.LARSSON    WTA311593    wta         12748     SWE
234            J.LEHECKA      ATPL0BV    atp         43155     CZE
235            J.LONDERO      ATPLB84    atp         26285     ARG
236             J.MCCABE      ATPM0OQ    atp             0     NaN
237             J.MENSIK      ATPM0NI    atp             0     NaN
238            J.MILLMAN      ATPMH30    atp         19769     AUS
239              J.MUNAR      ATPMU94    atp         33529     ESP
240           J.NIEMEIER    WTA325940    wta         40624     GER
241          J.OSTAPENKO    WTA319939    wta         28758     LAT
242            J.PAOLINI    WTA319280    wta         33206     ITA
243             J.PEGULA    WTA316956    wta         21863     USA
244           J.RODIONOV          NaN    atp         36384     AUT
245              J.SHANG      ATPS0RE    atp             0     NaN
246             J.SINNER      ATPS0AG    atp         39723     ITA
247              J.SMITH      ATPSJ55    atp             0     NaN
248               J.SOCK          NaN    atp         25481     USA
249              J.SOUSA      ATPSH90    atp         16392     POR
250             J.STRUFF      ATPSL28    atp         23386     GER
251          J.TEICHMANN    WTA320926    wta         31367     SUI
252           J.THOMPSON      ATPTC61    atp         28635     AUS
253             J.TSONGA      ATPT786    atp          6291     FRA
254           J.VARILLAS      ATPV836    atp         31166     PER
255             J.VESELY      ATPV708    atp         21741     CZE
256               J.WOLF      ATPW09G    atp         40399     USA
257                K.AHN    WTA316159    wta         23598     USA
258           K.ANDERSON      ATPA678    atp             0     NaN
259             K.BAINDL    WTA316739    wta             0     NaN
260            K.BERTENS    WTA314584    wta         17861     NED
261            K.BIRRELL    WTA320728    wta             0     NaN
262         K.BONDARENKO    WTA020702    wta             0     NaN
263            K.BOULTER    WTA319125    wta             0     NaN
264          K.COPPEJANS      ATPCG33    atp             0     NaN
265                K.DAY    WTA322534    wta         35699     USA
266             K.EDMUND      ATPE831    atp             0     NaN
267           K.FLIPKENS    WTA310331    wta             0     NaN
268              K.JUVAN    WTA324702    wta         40087     SLO
269             K.KANEPI    WTA110536    wta          5699     EST
270          K.KHACHANOV      ATPKE29    atp         29528     RUS
271            K.KOZLOVA    WTA316739    wta             0     NaN
272             K.KUCOVA    WTA312673    wta         14608     SVK
273          K.MAJCHRZAK      ATPMQ75    atp         31091     POL
274         K.MLADENOVIC    WTA315616    wta         19921     FRA
275            K.MUCHOVA    WTA322191    wta         35961     CZE
276               K.NARA          NaN    wta         17421     JPN
277          K.NISHIKORI      ATPN552    atp         13059     JPN
278           K.PLISKOVA    WTA313974    wta             0     NaN
279          K.RAKHIMOVA    WTA325936    wta         40622     ---
280              K.SEBOV    WTA322214    wta             0     NaN
281          K.SINIAKOVA    WTA320301    wta         28779     CZE
282           K.VOLYNETS    WTA327391    wta         42557     USA
283           K.ZAVATSKA          NaN    wta         38594     UKR
284          KA.PLISKOVA    WTA313974    wta         18274     CZE
285          KR.PLISKOVA    WTA313975    wta         18275     CZE
286             L.BROADY      ATPBI23    atp             0     NaN
287          L.BRONZETTI    WTA322280    wta         37977     ITA
288            L.CABRERA    WTA320013    wta             0     NaN
289              L.DAVIS    WTA317414    wta             0     NaN
290              L.DJERE      ATPDB63    atp         28518     SRB
291          L.FERNANDEZ    WTA326735    wta         43643     CAN
292        L.FRUHVIRTOVA    WTA329627    wta             0     NaN
293           L.GIUSTINO      ATPGA79    atp             0     NaN
294             L.HARRIS      ATPHG86    atp         33462     RSA
295           L.JEANJEAN    WTA320313    wta         24367     FRA

In [28]:
players_info_df = get_all_players_info_df('', league)
players_with_miss_id = players_info_df['player_name'][players_info_df['player_id_atp'].isna()]

players_with_miss_id = np.array(players_with_miss_id)
if not any(player is None for player in players_with_miss_id):
    print("No missing ATP IDs found.")
else:
    print("Missing ATP IDs found:", players_with_miss_id)

    print("Use this 'API' to find the PlayerId and add it to the players.csv in player_id_atp: https://www.atptour.com/en/-/www/site-search/SOCK/")
    raise ValueError("One or more players have a missing ID -> Players with missing ATP id: " + str(players_with_miss_id))

print("Players with missing atp id: ",  players_with_miss_id)

No missing ATP IDs found.
Players with missing atp id:  []